In [3]:
import os
import tarfile
from six.moves import urllib
import matplotlib.pyplot as plt

In [4]:
import pandas as pd

path=os.getcwd()
datapath="datasets"
netflix_raw=pd.read_csv(os.path.join(path,datapath,"netflix_titles.csv"))

In [4]:
#print(os.getcwd())

In [5]:
netflix_raw.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [51]:
netflix_raw.groupby('type').type.value_counts()

type     type
Movie    Movie      4265
TV Show  TV Show    1969
Name: type, dtype: int64

In [6]:
netflix_raw.describe()

            show_id  release_year
count  6.234000e+03    6234.00000
mean   7.670368e+07    2013.35932
std    1.094296e+07       8.81162
min    2.477470e+05    1925.00000
25%    8.003580e+07    2013.00000
50%    8.016337e+07    2016.00000
75%    8.024489e+07    2018.00000
max    8.123573e+07    2020.00000

In [7]:
netflix_raw.type.describe()

count      6234
unique        2
top       Movie
freq       4265
Name: type, dtype: object

In [8]:
netflix_raw.country.describe()

count              5758
unique              554
top       United States
freq               2032
Name: country, dtype: object

In [9]:
netflix_raw.rating.describe()

count      6224
unique       14
top       TV-MA
freq       2027
Name: rating, dtype: object

In [10]:
netflix_addedon = netflix_raw[['title','date_added']]

In [11]:
netflix_addedon.head()

                                     title         date_added
0  Norm of the North: King Sized Adventure  September 9, 2019
1               Jandino: Whatever it Takes  September 9, 2016
2                       Transformers Prime  September 8, 2018
3         Transformers: Robots in Disguise  September 8, 2018
4                             #realityhigh  September 8, 2017

In [5]:
imdb_akas=pd.read_csv(os.path.join(path,datapath,"imdb/title.akas.tsv/title.akas.tsv"), sep='\t', header=0)

/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
imdb_akas.head()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Carmencita - spanyol tánc,HU,\N,imdbDisplay,\N,0
1,tt0000001,2,Καρμενσίτα,GR,\N,\N,\N,0
2,tt0000001,3,Карменсита,RU,\N,\N,\N,0
3,tt0000001,4,Carmencita,US,\N,\N,\N,0
4,tt0000001,5,Carmencita,\N,\N,original,\N,1

In [7]:
imdb_ratings=pd.read_csv(os.path.join(path,datapath,"imdb/title.ratings.tsv/title.ratings.tsv"), sep='\t', header=0)

In [12]:
imdb_ratings.describe()

       averageRating      numVotes
count  993153.000000  9.931530e+05
mean        6.886546  9.556980e+02
std         1.400235  1.565733e+04
min         1.000000  5.000000e+00
25%         6.100000  9.000000e+00
50%         7.100000  2.000000e+01
75%         7.900000  7.600000e+01
max        10.000000  2.159745e+06

In [8]:
imdb_ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.6      1550
1  tt0000002            6.1       186
2  tt0000003            6.5      1207
3  tt0000004            6.2       113
4  tt0000005            6.1      1934

In [9]:
imdb_basics=pd.read_csv(os.path.join(path,datapath,"imdb/title.basics.tsv/title.basics.tsv"), sep='\t', header=0)

/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [11]:
imdb_basics.describe()

            isAdult
count  6.321302e+06
mean   3.309176e-02
std    2.537068e+00
min    0.000000e+00
25%    0.000000e+00
50%    0.000000e+00
75%    0.000000e+00
max    2.019000e+03

In [10]:
imdb_basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,\N,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"

In [18]:
'''
from sklearn.base import BaseEstimator, TransformerMixin

class join_dataframes (BaseEstimator ,TransformerMixin):
    def __init__(self):
        return None
    def fit(self):
        return self
    def transform(self ,leftdf ,leftindex ,rightdf ,rightindex):
        left = leftdf.set_index([leftindex])
        right = rightdf.set_index([rightindex])
        return left.join(right)
'''

'\nfrom sklearn.base import BaseEstimator, TransformerMixin\n\nclass join_dataframes (BaseEstimator ,TransformerMixin):\n    def __init__(self):\n        return None\n    def fit(self):\n        return self\n    def transform(self ,leftdf ,leftindex ,rightdf ,rightindex):\n        left = leftdf.set_index([leftindex])\n        right = rightdf.set_index([rightindex])\n        return left.join(right)\n'

In [19]:
def join_df(leftdf ,leftindex ,rightdf ,rightindex):
    left = leftdf.set_index([leftindex])
    right = rightdf.set_index([rightindex])
    return left.join(right)

In [20]:
imdb1 = join_df(imdb_akas ,'titleId' ,imdb_ratings ,'tconst')

In [1]:
imdb1.head()

NameError: name 'imdb1' is not defined

In [23]:
imdb_basics = imdb_basics.set_index(['tconst'])

In [24]:
imdb = imdb1.join(imdb_basics)

In [25]:
imdb.head()

,ordering,title,region,language,types,attributes,isOriginalTitle,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
tt0000001,1,Carmencita - spanyol tánc,HU,\N,imdbDisplay,\N,0,5.6,1550.0,short,Carmencita,Carmencita,0.0,1894,\N,1,"Documentary,Short"
tt0000001,2,Καρμενσίτα,GR,\N,\N,\N,0,5.6,1550.0,short,Carmencita,Carmencita,0.0,1894,\N,1,"Documentary,Short"
tt0000001,3,Карменсита,RU,\N,\N,\N,0,5.6,1550.0,short,Carmencita,Carmencita,0.0,1894,\N,1,"Documentary,Short"
tt0000001,4,Carmencita,US,\N,\N,\N,0,5.6,1550.0,short,Carmencita,Carmencita,0.0,1894,\N,1,"Documentary,Short"
tt0000001,5,Carmencita,\N,\N,original,\N,1,5.6,1550.0,short,Carmencita,Carmencita,0.0,1894,\N,1,"Documentary,Short"

In [26]:
imdb = imdb.set_index(['title'])

In [27]:
netflix_addedon = netflix_addedon.set_index(['title'])

In [29]:
base_copy = imdb.join(netflix_addedon)

In [66]:
netflix_type = netflix_raw[['title','type']].set_index(['title'])

In [67]:
netflix_type = imdb.join(netflix_type)

In [68]:
netflix_type.head()

,ordering,region,language,types,attributes,isOriginalTitle,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,type
title,,,,,,,,,,,,,,,,,
!Huff,8,US,\N,working,\N,0,7.9,3250.0,tvSeries,Huff,Huff,0.0,2004,2006,55,"Comedy,Drama",NaN
!Women Art Revolution,1,XWW,en,imdbDisplay,\N,0,6.8,198.0,movie,!Women Art Revolution,Women Art Revolution,0.0,2010,\N,83,Documentary,NaN
!Women Art Revolution,4,US,en,imdbDisplay,\N,0,6.8,198.0,movie,!Women Art Revolution,Women Art Revolution,0.0,2010,\N,83,Documentary,NaN
!mpossible,2,\N,\N,\N,orthographically correct title,0,6.3,35.0,tvSeries,Impossible,Impossible,0.0,2017,\N,44,Game-Show,NaN
#,1,US,\N,\N,\N,0,3.5,6.0,short,#,#,0.0,2012,\N,15,"Comedy,Short",NaN

In [69]:
netflix_type.reset_index()

,title,ordering,region,language,types,attributes,isOriginalTitle,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,type
0,!Huff,8,US,\N,working,\N,0,7.9,3250.0,tvSeries,Huff,Huff,0.0,2004,2006,55,"Comedy,Drama",NaN
1,!Women Art Revolution,1,XWW,en,imdbDisplay,\N,0,6.8,198.0,movie,!Women Art Revolution,Women Art Revolution,0.0,2010,\N,83,Documentary,NaN
2,!Women Art Revolution,4,US,en,imdbDisplay,\N,0,6.8,198.0,movie,!Women Art Revolution,Women Art Revolution,0.0,2010,\N,83,Documentary,NaN
3,!mpossible,2,\N,\N,\N,orthographically correct title,0,6.3,35.0,tvSeries,Impossible,Impossible,0.0,2017,\N,44,Game-Show,NaN
4,#,1,US,\N,\N,\N,0,3.5,6.0,short,#,#,0.0,2012,\N,15,"Comedy,Short",NaN
5,#,1,US,\N,\N,\N,0,NaN,NaN,short,#,#,0.0,2014,\N,\N,"Comedy,Short",NaN
6,#,3,XWW,en,festival,\N,0,NaN,NaN,movie,#Declimax,#Declimax,0.0,\N,\N,90,Drama,NaN
7,#,1,BR,\N,\N,\N,0,NaN,NaN,short,#,#,0.0,2012,\N,8,"Animation,Short",NaN
8,# En [Interchange],4,\N,\N,original,\N,1,NaN,NaN,video,# En [Interchange],# En [Interchange],1.0,2019,\N,128,Adult,NaN
9,# En [Interchange],5,JP,\N,\N,\N,0,NaN,NaN,video,# En [Interchange],# En [Interchange],1.0,2019,\N,128,Adult,NaN
10,# Mechanical Meany/A Chilly Furnace/Homerun Woody,1,US,\N,\N,\N,0,NaN,NaN,tvEpisode,# Mechanical Meany/A Chilly Furnace/Homerun Woody,# Mechanical Meany/A Chilly Furnace/Homerun Woody,0.0,2002,\N,\N,"Adventure,Animation,Comedy",NaN
11,# My Ass,1,US,\N,\N,\N,0,6.8,5.0,video,# My Ass,# My Ass,1.0,2015,\N,143,Adult,NaN
12,# Pire soirée,23,FR,\N,imdbDisplay,\N,0,5.2,41715.0,movie,Rough Night,Rough Night,0.0,2017,\N,101,"Comedy,Crime,Thriller",NaN
13,# Woodsy Woody/Chilly Solar Wars/Cue the Pool ...,1,US,\N,\N,\N,0,NaN,NaN,tvEpisode,# Woodsy Woody/Chilly Solar Wars/Cue the Pool ...,# Woodsy Woody/Chilly Solar Wars/Cue the Pool ...,0.0,2002,\N,\N,"Adventure,Animation,Comedy",NaN
14,##### puhelinmyyjät!,2,FI,\N,\N,first season title,0,4.1,15.0,tvSeries,V###n puhelinmyyjät!,V###n puhelinmyyjät!,0.0,2015,\N,60,Reality-TV,NaN
15,#1,1,US,\N,\N,\N,0,6.4,12.0,short,#1,#1,0.0,2005,\N,30,"Drama,Short",NaN
16,#1,1,US,\N,\N,\N,0,NaN,NaN,video,#1,#1,0.0,2010,\N,12,"Comedy,Drama,News",NaN
17,#1,1,US,\N,\N,\N,0,NaN,NaN,video,#1,#1,0.0,2010,\N,3,"Animation,Drama,Short",NaN
18,#1,1,US,\N,\N,\N,0,NaN,NaN,short,#1,#1,0.0,2010,\N,12,"Comedy,Short",NaN
19,#1,1,BE,\N,\N,\N,0,NaN,NaN,short,#1,#1,0.0,2009,\N,4,"Animation,Short",NaN
20,#1,1,US,\N,\N,\N,0,NaN,NaN,movie,#1,#1,0.0,\N,\N,\N,Documentary,NaN
21,#1 Beauty Nail Salon,1,US,\N,\N,\N,0,NaN,NaN,short,#1 Beauty Nail Salon,#1 Beauty Nail Salon,0.0,2014,\N,5,"Drama,History,Short",NaN
22,#1 Cheerleader Camp,3,US,\N,imdbDisplay,\N,0,3.7,2907.0,video,#1 Cheerleader Camp,#1 Cheerleader Camp,0.0,2010,\N,95,Comedy,NaN
23,#1 Cheerleader Camp,4,\N,\N,original,\N,1,3.7,2907.0,video,#1 Cheerleader Camp,#1 Cheerleader Camp,0.0,2010,\N,95,Comedy,NaN
24,#1 Dad,1,US,\N,\N,\N,0,NaN,NaN,short,#1 Dad,#1 Dad,0.0,2016,\N,7,"Comedy,Short",NaN
25,#1 Fan,1,US,\N,\N,\N,0,7.8,165.0,tvEpisode,#1 Fan,#1 Fan,0.0,2017,\N,41,"Crime,Drama,Mystery",NaN
26,#1 Fan: A Darkomentary,1,US,\N,\N,\N,0,7.9,168.0,video,#1 Fan: A Darkomentary,#1 Fan: A Darkomentary,0.0,2005,\N,13,"Comedy,Short",NaN
27,#1 Hits,1,US,\N,\N,\N,0,NaN,NaN,tvEpisode,#1 Hits,#1 Hits,0.0,2010,\N,60,Music,NaN
28,#1 Mamarazzi,1,US,\N,\N,\N,0,NaN,NaN,movie,#1 Mamarazzi,#1 Mamarazzi,0.0,\N,\N,\N,Comedy,NaN
29,#1 Serial Killer,2,\N,\N,original,\N,1,5.6,40.0,movie,#1 Serial Killer,#1 Serial Killer,0.0,2013,\N,87,Horror,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19325289,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,1981,\N,\N,"Family,Game-Show,Reality-TV",NaN
19325290,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,2011,\N,\N,"Comedy,Music,Talk-Show",NaN
19325291,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,1992,\N,\N,"Family,Game-Show,Short",NaN
19325292,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,2012,\N,\N,"Comedy,Drama,Music",NaN
19325293,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,1993,\N,\N,"Game-Show,Short",NaN
19325294,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,2013,\N,\N,"Comedy,Music,News",NaN
19325295,エピソード #9.99,2,JP,ja,\N,\N,0,9.8,36.0,tvEpisode,Episode #9.99,Episode #9.99,0.0,2011,\N,\N,Documentary,NaN
19325296,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,2014,\N,\N,"Adventure,Drama,Romance",NaN
19325297,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,2014,\N,\N,Family,NaN
19325298,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,2002,\N,\N,"Comedy,Music,Talk-Show",NaN
19325299,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,1970,\N,\N,"Comedy,Music,Talk-Show",NaN
19325300,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,1984,\N,\N,Game-Show,NaN
19325301,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,2018,\N,37,"Comedy,Family,Game-Show",NaN
19325302,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,2018,\N,\N,Sci-Fi,NaN
19325303,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,2018,\N,120,"News,Sport,Talk-Show",NaN
19325304,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,2018,\N,\N,Comedy,NaN
19325305,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,2018,\N,\N,Talk-Show,NaN
19325306,エピソード #9.99,2,JP,ja,\N,\N,0,NaN,NaN,tvEpisode,Episode #9.99,Episode #9.99,0.0,1992,\N,\N,"Reality-TV,Romance",NaN
19325307,ジョーカー,6,JP,ja,imdbDisplay,\N,0,8.8,466912.0,movie,Joker,Joker,0.0,2019,\N,122,"Crime,Drama,Thriller",NaN
19325308,テストムービー,41,JP,ja,imdbDisplay,\N,0,7.2,74.0,movie,Testing Movie1,Testing Movie1,0.0,2010,\N,123,"Adventure,Animation,Biography",NaN
19325309,パリに見出されたピアニスト,7,JP,ja,imdbDisplay,\N,0,6.3,540.0,movie,In Your Hands,Au bout des doigts,0.0,2018,\N,105,"Drama,Romance",NaN
19325310,ブルース・ブラザース,7,JP,ja,imdbDisplay,\N,0,7.9,171076.0,movie,The Blues Brothers,The Blues Brothers,0.0,1980,\N,133,"Adventure,Comedy,Crime",NaN
19325311,ブルーノート・レコード ジャズを超えて,1,JP,ja,imdbDisplay,\N,0,7.3,209.0,movie,Blue Note Records: Beyond the Notes,Blue Note Records: Beyond the Notes,0.0,2018,\N,85,"Documentary,Music",NaN
19325312,マレフィセント2,2,JP,ja,imdbDisplay,\N,0,7.0,24717.0,movie,Maleficent: Mistress of Evil,Maleficent: Mistress of Evil,0.0,2019,\N,119,"Adventure,Family,Fantasy",NaN
19325313,ロボット2.0,5,JP,ja,imdbDisplay,\N,0,6.4,19042.0,movie,2.0,2.0,0.0,2018,\N,148,"Action,Sci-Fi",NaN
19325314,劇場版 BanG Dream! FILM LIVE,2,JP,ja,imdbDisplay,\N,0,NaN,NaN,movie,BanG Dream! FILM LIVE,BanG Dream! FILM LIVE,0.0,2019,\N,73,"Animation,Comedy,Fantasy",NaN
19325315,测试电影,30,HK,zh,imdbDisplay,\N,0,7.2,74.0,movie,Testing Movie1,Testing Movie1,0.0,2010,\N,123,"Adventure,Animation,Biography",NaN
19325316,測試電影,50,CN,zh,imdbDisplay,\N,0,7.2,74.0,movie,Testing Movie1,Testing Movie1,0.0,2010,\N,123,"Adventure,Animation,Biography",NaN
19325317,米軍（アメリカ）が最も恐れた男 カメジロー不屈の生涯,1,JP,ja,imdbDisplay,\N,0,NaN,NaN,movie,"Beigun ga mottomo osoreta otoko, sono na wa Ka...","Beigun ga mottomo osoreta otoko, sono na wa Ka...",0.0,2017,\N,107,Documentary,NaN
19325318,영화 테스트,8,KR,ko,imdbDisplay,\N,0,7.2,74.0,movie,Testing Movie1,Testing Movie1,0.0,2010,\N,123,"Adventure,Animation,Biography",NaN

In [70]:
netflix_type.groupby('type').apply(lambda x: x.type=='Movie').agg('sum')

29021

In [53]:
netflix_raw.groupby('type').apply(lambda x: x.type=='Movie').agg('sum')

4265

In [30]:
base = base_copy.copy()

In [1]:
base.head()

NameError: name 'base' is not defined

In [32]:
base.startYear.unique()

array(['2004', '2010', '2017', '2012', '2014', '\\N', '2019', '2002',
       '2015', '2005', '2009', '2016', '2013', '2006', '2011', '1984',
       '1975', '2007', '1985', '2021', '2018', '2008', nan, '2000',
       '1963', '2020', '1971', 1923, '1913', '1915', 1966, '1986', 1971,
       1937, '2001', 1935, 1967, '1921', 1921, 1959, '1989', 1965, 1968,
       1939, '2003', 1924, '1996', '1911', '1941', '1903', '1999', '1920',
       '1974', '1995', 1916, 1918, 1949, '1919', '1909', '1980', '1983',
       '1993', '1994', '1979', '1972', '1968', '1951', '1997', 1917,
       '1988', '1992', '1973', 1920, '1982', '1922', '1924', '1987', 1961,
       1928, '1960', '1912', '1905', '1932', '1914', '1977', '1897', 1913,
       '1901', '1953', '1952', 1915, '1990', 1947, '1964', '1965', 1969,
       '1966', '1978', '1935', '1899', '1945', '1900', '1908', 1914,
       '1938', '1961', '1902', '1991', '1962', '1981', 1942, 1936, '1944',
       '1950', '1955', '1958', '1954', '1907', '1969', '1998', '1957',
       '1927', 1943, '1930', '1937', '1946', 1960, '1959', '1967', 1929,
       '1898', '1970', '1926', 1973, '1931', 1957, '1910', 1954, 1938,
       1934, 1946, '1925', 1926, 1940, '1923', '1917', '1916', 1908, 1964,
       1941, '1904', 1962, '1939', '1918', 1922, '1947', '1948', 1951,
       '1929', 1952, '1956', '1940', '1976', '1933', 1909, '1934', '1928',
       1911, '1906', 1958, 1930, 1955, 1948, 1932, 1919, 1953, 1950,
       '1936', 1956, '1896', 1963, 1944, 1945, 1970, '1943', 1933, 1931,
       1927, '1949', '1942', '2115', 1896, 1907, 1925, '2022', 1986, 1895,
       1972, '1894', 1912, 1897, 1910, 1903, 1905, 1904, 1894, 1899,
       '1895', 1892, '1892', 1906, 1898, 1902, 1901, '1890', 1900, 1893,
       '1888', '2026', '2024', 1990, 1983, 1974, 1977, 1981, '2023',
       '2025', '2027', '1887', 1976, 1979, 1978, '1883', 2001, 1975, 1992,
       1989, 1995, 1988, 1993, '1891', '1893', '1889', '1878', '1874',
       1985], dtype=object)

In [39]:
#del data

In [36]:
import numpy as np

In [40]:
base['startYear'] = np.where((base.startYear.isnull()) | (base.startYear=='\\N') 
                               ,0 ,base.startYear).astype('int64')

In [41]:
base = base.sort_values(by='startYear').reset_index(drop=True)

In [102]:
data = base.copy()

In [ ]:
data.head()

In [43]:
data.dtypes

ordering             int64
region              object
language            object
types               object
attributes          object
isOriginalTitle     object
averageRating      float64
numVotes           float64
titleType           object
primaryTitle        object
originalTitle       object
isAdult            float64
startYear            int64
endYear             object
runtimeMinutes      object
genres              object
date_added          object
dtype: object

In [103]:
data = data.loc[data.startYear!=0]

In [104]:
data = data.loc[data.runtimeMinutes!='\\N']

In [105]:
data = data.loc[data.titleType!='videoGame']

In [106]:
data[['titleType']] = data[['titleType']].fillna('\\N')

In [107]:
data[['isOriginalTitle','isAdult']] = data[['isOriginalTitle','isAdult']].astype('bool')

In [108]:
data[['runtimeMinutes','endYear']] = data[['runtimeMinutes','endYear']].apply(lambda x: np.where(x.isnull() | (x=='\\N') ,0 ,x) ,axis=0).astype('int64')

In [94]:
#pd.DatetimeIndex(data['runtimeMinutes']).minute

In [95]:
data.head()

,ordering,region,language,types,attributes,isOriginalTitle,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,date_added
1375654,1,RS,\N,imdbDisplay,\N,True,7.0,1012.0,short,Passage de Venus,Passage de Venus,False,1874,0,1,"Documentary,Short",NaN
1375655,5,CZ,\N,\N,\N,True,7.0,1012.0,short,Passage de Venus,Passage de Venus,False,1874,0,1,"Documentary,Short",NaN
1375656,3,RU,\N,\N,\N,True,7.0,1012.0,short,Passage de Venus,Passage de Venus,False,1874,0,1,"Documentary,Short",NaN
1375657,8,XWW,en,\N,informal literal English title,True,7.0,1012.0,short,Passage de Venus,Passage de Venus,False,1874,0,1,"Documentary,Short",NaN
1375658,4,US,\N,imdbDisplay,\N,True,7.0,1012.0,short,Passage de Venus,Passage de Venus,False,1874,0,1,"Documentary,Short",NaN

In [110]:
data['yearsRun'] =  (np.where(data.endYear==0 ,data.startYear ,data.endYear) - data.startYear).astype('int64')

In [111]:
data.yearsRun.unique()

array([ 0, 12,  4,  9,  2,  1, 10,  3,  7, 16,  8, 24,  6, 13, 11, 19, 23,
        5, 31, 14, 15, 17, 38, 43, 37, 20, 35, 65, 48, 21, 29, 34, 57, 18,
       36, 41, 22, 66, 30, 25, 54, 27, 28, 32, 42, 49, 44, 56, 46, 52, 53,
       26, 40, 45, 33, 39])

In [112]:
data[['date_added']] =  np.where(data.date_added.isnull() 
                                 ,'0' ,data.date_added.str[-4:]).astype('int64')

In [113]:
data['yearsToAdd'] =  np.where((data.startYear==0) | (data.date_added==0),0, data.date_added-data.startYear)

In [284]:
data['runtime_cat'] = pd.cut(data.runtimeMinutes
       ,bins=[-1 ,30 ,60 ,90 ,120 ,180 ,np.inf]
       ,labels=['0-30' ,'30-60' ,'60-90' ,'90-120' ,'120-180', 'Long'])

In [285]:
data.dtypes

ordering              int64
region               object
language             object
types                object
attributes           object
isOriginalTitle        bool
averageRating       float64
numVotes            float64
titleType            object
primaryTitle         object
originalTitle        object
isAdult                bool
startYear             int64
endYear               int64
runtimeMinutes        int64
genres               object
date_added            int64
yearsRun              int64
yearsToAdd            int64
runtime_cat        category
dtype: object

In [118]:
data.head()

,ordering,region,language,types,attributes,isOriginalTitle,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,date_added,yearsRun,yearsToAdd,runtime_cat
1375654,1,RS,\N,imdbDisplay,\N,True,7.0,1012.0,short,Passage de Venus,Passage de Venus,False,1874,0,1,"Documentary,Short",0,0,0,0-30
1375655,5,CZ,\N,\N,\N,True,7.0,1012.0,short,Passage de Venus,Passage de Venus,False,1874,0,1,"Documentary,Short",0,0,0,0-30
1375656,3,RU,\N,\N,\N,True,7.0,1012.0,short,Passage de Venus,Passage de Venus,False,1874,0,1,"Documentary,Short",0,0,0,0-30
1375657,8,XWW,en,\N,informal literal English title,True,7.0,1012.0,short,Passage de Venus,Passage de Venus,False,1874,0,1,"Documentary,Short",0,0,0,0-30
1375658,4,US,\N,imdbDisplay,\N,True,7.0,1012.0,short,Passage de Venus,Passage de Venus,False,1874,0,1,"Documentary,Short",0,0,0,0-30

In [120]:
data.shape

(3611377, 20)

In [121]:
data.loc[data.yearsToAdd<0]

,ordering,region,language,types,attributes,isOriginalTitle,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,date_added,yearsRun,yearsToAdd,runtime_cat
12170374,1,XWW,en,\N,\N,True,6.9,146.0,movie,Just Another Love Story,Aarekti Premer Golpo,False,2010,0,128,Drama,2009,0,-1,120-180
13883057,1,\N,\N,original,\N,True,5.2,22.0,movie,Splatter,Splatter,False,2012,0,53,"Horror,Mystery,Thriller",2009,0,-3,30-60
13883095,2,UA,\N,\N,\N,False,5.2,22.0,movie,Splatter,Splatter,False,2012,0,53,"Horror,Mystery,Thriller",2009,0,-3,30-60
14308472,1,GB,\N,\N,\N,True,NaN,NaN,short,White Christmas,White Christmas,False,2013,0,7,"Comedy,Short",2012,0,-1,0-30
15018969,1,GB,\N,\N,\N,True,NaN,NaN,short,Splatter,Splatter,False,2014,0,3,Short,2009,0,-5,0-30
15460210,2,\N,\N,original,\N,True,9.2,44872.0,tvEpisode,White Christmas,White Christmas,False,2014,0,73,"Drama,Sci-Fi,Thriller",2012,0,-2,60-90
15460214,3,GB,\N,\N,\N,True,9.2,44872.0,tvEpisode,White Christmas,White Christmas,False,2014,0,73,"Drama,Sci-Fi,Thriller",2012,0,-2,60-90
15460221,1,US,\N,imdbDisplay,\N,True,9.2,44872.0,tvEpisode,White Christmas,White Christmas,False,2014,0,73,"Drama,Sci-Fi,Thriller",2012,0,-2,60-90
16013904,1,US,\N,\N,\N,True,9.2,17.0,short,Splatter,Splatter,False,2015,0,24,"Drama,Short",2009,0,-6,0-30
16173656,1,US,\N,imdbDisplay,\N,True,8.3,1076.0,tvEpisode,White Christmas,White Christmas,False,2015,0,21,"Comedy,Romance",2012,0,-3,0-30
16173667,2,\N,\N,original,\N,True,8.3,1076.0,tvEpisode,White Christmas,White Christmas,False,2015,0,21,"Comedy,Romance",2012,0,-3,0-30
16236912,6,\N,\N,original,\N,True,6.3,75153.0,movie,Goosebumps,Goosebumps,False,2015,0,103,"Adventure,Comedy,Family",2014,0,-1,90-120
16236913,24,AU,\N,imdbDisplay,\N,False,6.3,75153.0,movie,Goosebumps,Goosebumps,False,2015,0,103,"Adventure,Comedy,Family",2014,0,-1,90-120
16236914,1,US,\N,imdbDisplay,\N,False,6.3,75153.0,movie,Goosebumps,Goosebumps,False,2015,0,103,"Adventure,Comedy,Family",2014,0,-1,90-120
16236915,19,GB,\N,imdbDisplay,\N,False,6.3,75153.0,movie,Goosebumps,Goosebumps,False,2015,0,103,"Adventure,Comedy,Family",2014,0,-1,90-120
16236916,14,IE,en,imdbDisplay,\N,False,6.3,75153.0,movie,Goosebumps,Goosebumps,False,2015,0,103,"Adventure,Comedy,Family",2014,0,-1,90-120
16236917,13,CA,en,imdbDisplay,\N,False,6.3,75153.0,movie,Goosebumps,Goosebumps,False,2015,0,103,"Adventure,Comedy,Family",2014,0,-1,90-120
16237547,3,DE,\N,\N,soft porn version,True,NaN,NaN,video,Housemates 2,Housemates 2,True,2015,0,95,"Adult,Drama,Romance",2011,0,-4,90-120
16381365,1,AU,\N,\N,\N,True,NaN,NaN,short,Circle,Circle,False,2016,0,15,"Drama,Short",2015,0,-1,0-30
16381565,1,IT,\N,\N,\N,True,NaN,NaN,movie,Circle,Circle,False,2016,0,70,"Documentary,Family",2015,0,-1,60-90
16381580,1,DE,\N,\N,\N,True,7.3,10.0,short,Circle,Circle,False,2016,0,12,"Animation,Drama,Fantasy",2015,0,-1,0-30
16381586,1,NL,\N,\N,\N,True,NaN,NaN,short,Circle,Circle,False,2016,0,6,"Animation,Short",2015,0,-1,0-30
16381592,1,IR,\N,\N,\N,True,NaN,NaN,short,Circle,Circle,False,2016,0,20,"Drama,Family,Short",2015,0,-1,0-30
16405080,1,US,\N,\N,\N,True,NaN,NaN,short,Creep,Creep,False,2016,0,7,"Adventure,Animation,Comedy",2015,0,-1,0-30
16805606,1,US,\N,\N,\N,True,NaN,NaN,short,Star-Crossed,Star-Crossed,False,2016,0,9,"Drama,Romance,Short",2015,0,-1,0-30
16805608,3,\N,\N,original,\N,True,8.0,615.0,tvEpisode,Star-Crossed,Star-Crossed,False,2016,0,43,"Drama,Fantasy,Horror",2015,0,-1,30-60
16805619,2,US,\N,\N,\N,True,8.0,615.0,tvEpisode,Star-Crossed,Star-Crossed,False,2016,0,43,"Drama,Fantasy,Horror",2015,0,-1,30-60
16849086,5,XWW,en,imdbDisplay,\N,True,6.9,33.0,movie,Finding Santa,Den magiske juleæske,False,2016,0,80,"Animation,Family",2014,0,-2,60-90
16860415,1,US,\N,\N,\N,True,NaN,NaN,video,Haschak Sisters: Gossip Girl,Haschak Sisters: Gossip Girl,False,2016,0,3,"Music,Short",2013,0,-3,0-30
16877431,1,IT,\N,\N,\N,True,NaN,NaN,tvEpisode,Some Assembly Required,Some Assembly Required,False,2016,0,11,Animation,2015,0,-1,0-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19275430,1,\N,\N,original,\N,True,NaN,NaN,short,Requiem,Requiem,False,2019,0,13,"Drama,Short,Thriller",2018,0,-1,0-30
19275449,1,CA,\N,\N,\N,False,NaN,NaN,short,Requiem,Requiem,False,2019,0,14,"Drama,Sci-Fi,Short",2018,0,-1,0-30
19277748,1,US,\N,\N,\N,False,NaN,NaN,short,Requiem,Requiem,False,2019,0,1,Short,2018,0,-1,0-30
19284973,1,RS,\N,\N,\N,True,NaN,NaN,movie,Revolt,Revolt,False,2019,0,80,Drama,2018,0,-1,60-90
19286999,1,AU,\N,\N,\N,True,NaN,NaN,tvEpisode,Results,Results,False,2019,0,25,Comedy,2015,0,-4,0-30
19299626,3,GB,\N,alternative,\N,True,NaN,NaN,movie,Grim Hollow,Grim Hollow,False,2020,0,90,"Action,Adventure,Animation",2018,0,-2,60-90
19299845,1,US,\N,\N,\N,True,NaN,NaN,movie,Rebirth,Rebirth,False,2020,0,90,Thriller,2016,0,-4,60-90
19300469,1,IN,\N,\N,\N,True,NaN,NaN,movie,Hera Pheri,Hera Pheri,False,2020,0,122,Drama,2019,0,-1,120-180
19301866,1,CA,\N,\N,\N,True,NaN,NaN,short,Zoo,Zoo,False,2020,0,12,"Action,Short",2018,0,-2,0-30
19301867,1,CA,\N,\N,\N,True,NaN,NaN,short,Zoo,Zoo,False,2020,0,12,"Action,Short",2017,0,-3,0-30
19302324,1,CY,\N,\N,\N,True,NaN,NaN,short,The Hunt,The Hunt,False,2020,0,21,"Drama,Short,Thriller",2017,0,-3,0-30
19304203,1,US,\N,\N,\N,True,NaN,NaN,short,The Promise,The Promise,False,2020,0,20,"Drama,Short",2018,0,-2,0-30
19304776,2,\N,\N,working,\N,True,NaN,NaN,movie,Manhunt,Manhunt,False,2020,0,71,"Action,Thriller",2016,0,-4,60-90
19305583,1,US,\N,\N,\N,True,NaN,NaN,movie,Garbage,Garbage,False,2020,0,67,Comedy,2018,0,-2,60-90
19307822,1,US,\N,\N,\N,True,NaN,NaN,short,Broken,Broken,False,2020,0,15,"Drama,Short",2019,0,-1,0-30
19308681,1,US,\N,\N,\N,True,NaN,NaN,movie,Frontier,Frontier,False,2020,0,95,Western,2018,0,-2,90-120
19309567,3,\N,\N,original,\N,True,NaN,NaN,movie,Manhunt,Manhunt,False,2020,0,71,"Action,Thriller",2017,0,-3,60-90
19309568,3,\N,\N,original,\N,True,NaN,NaN,movie,Manhunt,Manhunt,False,2020,0,71,"Action,Thriller",2018,0,-2,60-90
19309569,5,US,\N,\N,\N,True,NaN,NaN,movie,Manhunt,Manhunt,False,2020,0,71,"Action,Thriller",2017,0,-3,60-90
19309570,5,US,\N,\N,\N,True,NaN,NaN,movie,Manhunt,Manhunt,False,2020,0,71,"Action,Thriller",2018,0,-2,60-90
19310976,1,US,\N,\N,\N,True,NaN,NaN,short,After,After,False,2020,0,18,Short,2019,0,-1,0-30
19312795,1,US,\N,\N,\N,False,NaN,NaN,short,The Box,The Box,False,2020,0,20,"Drama,Short",2019,0,-1,0-30
19316539,1,US,\N,\N,\N,False,NaN,NaN,short,Blind Date,Blind Date,False,2020,0,20,Short,2016,0,-4,0-30
19319864,1,US,\N,\N,\N,False,NaN,NaN,movie,Revolt,Revolt,False,2020,0,96,"Action,Drama,Thriller",2018,0,-2,90-120
19320329,1,GB,\N,\N,\N,False,NaN,NaN,short,Walk with Me,Walk with Me,False,2020,0,8,"Mystery,Short",2017,0,-3,0-30
19321704,2,US,\N,imdbDisplay,\N,True,NaN,NaN,tvSeries,Snowpiercer,Snowpiercer,False,2020,0,60,"Action,Drama,Sci-Fi",2019,0,-1,30-60
19321707,3,\N,\N,original,\N,True,NaN,NaN,tvSeries,Snowpiercer,Snowpiercer,False,2020,0,60,"Action,Drama,Sci-Fi",2019,0,-1,30-60
19321708,4,GB,\N,imdbDisplay,\N,True,NaN,NaN,tvSeries,Snowpiercer,Snowpiercer,False,2020,0,60,"Action,Drama,Sci-Fi",2019,0,-1,30-60
19325010,2,\N,\N,original,\N,True,NaN,NaN,movie,Hide & Seek,Hide & Seek,False,2021,0,100,"Adventure,Crime,Drama",2018,0,-3,90-120
19325011,1,GB,\N,\N,\N,True,NaN,NaN,movie,Hide & Seek,Hide & Seek,False,2021,0,100,"Adventure,Crime,Drama",2018,0,-3,90-120

In [122]:
genres = pd.DataFrame(columns=['genre0','genre1','genre2'])

In [123]:
genres[['genre0','genre1','genre2']] = data.genres.str.split(',',expand=True)

In [2554]:
list(genres.genre0)

['Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Short',
 'Short',
 'Documentary',
 'Short',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Short',
 'Short',
 'Documentary',
 'Short',
 'Short',
 'Short',
 'Documentary',
 'Short',
 'Short',
 'Short',
 'Short',
 'Short',
 'Short',
 'Action',
 'Action',
 'Short',
 'Short',
 'Short',
 'Short',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 'Action',
 'Action',
 'Short',
 'Short',
 'Short',
 'Short',
 'Animation',
 'Short',
 'Animation',
 'Animation',
 'Short',
 'Short',
 'Short',
 'Short',
 'Animation',
 'Animation',
 'Short',
 'Animation',
 'Animation',
 'Animation',
 'Short',
 'Animation',
 'Short',
 'Animation',
 'Animation',
 'Animation',
 'Short',
 'Comedy',
 'Comedy',
 'Comedy',
 'Comedy',
 'Comedy',
 'Comedy',
 'Comedy',
 'Comedy',
 'Comedy',
 'Comedy',
 'Short',
 'Romance',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Romance',
 'Comedy',
 'Documentary',
 'Comedy',
 'Comedy',
 'Romance',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Music',
 'Music',
 'Documentary',
 'Drama',
 'Short',
 'Short',
 'Documentary',
 'Short',
 'Short',
 'Comedy',
 'Documentary',
 'Animation',
 'Documentary',
 'Animation',
 'Documentary',
 'Documentary',
 'Animation',
 'Animation',
 'Short',
 'Music',
 'Short',
 'Action',
 'Short',
 'Short',
 'Documentary',
 'Documentary',
 'Music',
 'Short',
 'Short',
 'Documentary',
 'Comedy',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Music',
 'Comedy',
 'Documentary',
 'Comedy',
 'Documentary',
 'Action',
 'Documentary',
 'Music',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 'Short',
 'Documentary',
 'Documentary',
 'Animation',
 'Short',
 'Short',
 'Short',
 'Short',
 'Short',
 'Documentary',
 'Short',
 'Documentary',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Short',
 'Short',
 'Documentary',
 'Short',
 'Short',
 'Short',
 'Comedy',
 'Action',
 'Short',
 'Short',
 'Short',
 'Drama',
 'Short',
 'Short',
 'Drama',
 'Short',
 'Short',
 'Short',
 'Documentary',
 'Short',
 'Comedy',
 'Short',
 'Action',
 'Action',
 'Comedy',
 'Documentary',
 'Documentary',
 'Short',
 'Action',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 'Short',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 'Short',
 'Documentary',
 'Short',
 'Comedy',
 'Comedy',
 'Comedy',
 'Short',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Crime',
 'Documentary',
 'Documentary',
 'Short',
 'Short',
 'Documentary',
 'Comedy',
 'Documentary',
 'Short',
 'Crime',
 'Documentary',
 'Documentary',
 'Comedy',
 'Comedy',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Short',
 'Comedy',
 'Short',
 'Short',
 'Comedy',
 'History',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'History',
 'Documentary',
 'Short',
 'Crime',
 'Documentary',
 'Documentary',
 'Crime',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'History',
 'Documentary',
 'Crime',
 'Crime',
 'Short',
 'Documentary',
 'Crime',
 'Documentary',
 'Crime',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Comedy',
 'History',
 'Documentary',
 'Documentary',
 'Comedy',
 'Documentary',
 'Comedy',
 'Short',
 'Short',
 'Comedy',
 'Documentary',
 'Comedy',
 'Documentary',
 'Short',
 'History',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Short',
 'Comedy',
 'Documentary',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'History',
 'History',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Short',
 'Documentary',
 'Comedy',
 'Documentary',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'History',
 'Documentary',
 'Comedy',
 'Documentary',
 'Short',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Comedy',
 'Short',
 'Comedy',
 'Documentary',
 'Documentary',
 'Comedy',
 'Comedy',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'History',
 'Short',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Comedy',
 'Comedy',
 'Documentary',
 'Comedy',
 'Comedy',
 'Comedy',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Comedy',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Comedy',
 'Comedy',
 'Documentary',
 'Documentary',
 'Romance',
 'Comedy',
 'Short',
 'Romance',
 'Documentary',
 'Romance',
 'Romance',
 'Short',
 'Drama',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Short',
 'Documentary',
 'Comedy',
 'Documentary',
 'Horror',
 'Comedy',
 'Horror',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Romance',
 'Short',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 'Action',
 'Romance',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Documentary',
 'Horror',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Short',
 'Documentary',
 'Comedy',
 'Documentary',
 'Documentary',
 'Comedy',
 'Documentary',
 'Comedy',
 'Comedy',
 'Drama',
 'Short',
 'Drama',
 'Family',
 'Family',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Drama',
 'Horror',
 'Biography',
 'Documentary',
 'Short',
 'Horror',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Comedy',
 'Comedy',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 'Drama',
 'Drama',
 'Documentary',
 'Fantasy',
 'Fantasy',
 'Fantasy',
 'Drama',
 'Horror',
 'Drama',
 'Short',
 'Documentary',
 'Documentary',
 'Short',
 'Short',
 'Documentary',
 'Comedy',
 'Short',
 'Documentary',
 'Comedy',
 'Horror',
 'Comedy',
 'Comedy',
 'Drama',
 'Short',
 'Short',
 'Horror',
 'Documentary',
 'Short',
 'Horror',
 'Documentary',
 'Fantasy',
 'Fantasy',
 'Fantasy',
 'Action',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Drama',
 'Documentary',
 'Drama',
 'Documentary',
 'Documentary',
 'Action',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Action',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Fantasy',
 'Fantasy',
 'Action',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Family',
 'Documentary',
 'Documentary',
 'Family',
 'Documentary',
 'Short',
 'Short',
 'Short',
 'Horror',
 'Documentary',
 'Documentary',
 'Short',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Action',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Action',
 'Documentary',
 'Horror',
 'Short',
 'Horror',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Drama',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Comedy',
 'Comedy',
 'Comedy',
 'Horror',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Drama',
 'Drama',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 'Drama',
 'Documentary',
 'Documentary',
 'Drama',
 'Documentary',
 'Short',
 'Short',
 'Horror',
 'Documentary',
 'Short',
 'Horror',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Horror',
 'Documentary',
 'Action',
 'Comedy',
 'Documentary',
 'Documentary',
 'Comedy',
 'Comedy',
 'Documentary',
 'Action',
 'Comedy',
 'Biography',
 'Documentary',
 'Family',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Action',
 'Documentary',
 'Comedy',
 'Short',
 'Short',
 'Short',
 'Documentary',
 'Documentary',
 'Romance',
 'Documentary',
 'Documentary',
 'Horror',
 'Crime',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Romance',
 'Documentary',
 'Documentary',
 'Action',
 'Short',
 'Horror',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Biography',
 'Romance',
 'Documentary',
 'Documentary',
 'Short',
 'Comedy',
 'Comedy',
 'Documentary',
 'Biography',
 'Action',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Drama',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Documentary',
 'Short',
 'Documentary',
 'Action',
 'Horror',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Romance',
 'Short',
 'Comedy',
 'Documentary',
 'Romance',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Drama',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Romance',
 'Documentary',
 'Documentary',
 'Biography',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Fantasy',
 'Documentary',
 'Drama',
 'Fantasy',
 'Fantasy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Comedy',
 'Horror',
 'Romance',
 'Biography',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Horror',
 'Documentary',
 'Documentary',
 'Documentary',
 'Action',
 'Comedy',
 'Short',
 'Short',
 'Short',
 'Documentary',
 'Short',
 'Documentary',
 'Horror',
 'Romance',
 'Biography',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Action',
 'Horror',
 'Documentary',
 'News',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Short',
 'Documentary',
 'Documentary',
 'Action',
 'Documentary',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Drama',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 'Comedy',
 'Documentary',
 'Documentary',
 'Comedy',
 'Comedy',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Documentary',
 'Short',
 'Documentary',
 'Short',
 ...]

In [124]:
genres['genre0'] = np.where(genres.genre0.isnull(),'\\N' ,genres.genre0)
genres['genre1'] = np.where(genres.genre1.isnull(),'\\N' ,genres.genre1)
genres['genre2'] = np.where(genres.genre2.isnull(),'\\N' ,genres.genre2)

In [2557]:
genres

               genre0     genre1   genre2
1375654   Documentary      Short       \N
1375655   Documentary      Short       \N
1375656   Documentary      Short       \N
1375657   Documentary      Short       \N
1375658   Documentary      Short       \N
...               ...        ...      ...
19325260       Action  Adventure   Horror
19325265        Drama      Short       \N
19325276        Drama    Fantasy  Romance
19325281        Drama    Fantasy  Romance
19325291    Animation         \N       \N

[3611377 rows x 3 columns]

In [125]:
genres_unique = pd.DataFrame(columns=['0'])

In [126]:
genres_unique['0'] = list(genres['genre0']) + list(genres['genre1']) + list(genres['genre2'])

In [127]:
genres_unique.shape

(10834131, 1)

In [128]:
genres_uniq = pd.DataFrame(columns=['0'])

In [129]:
genres_uniq['0'] = genres_unique['0'].unique()

In [130]:
genres_uniq = genres_uniq.sort_values(by='0').reset_index(drop=True)

In [135]:
genres_uniq

              0
0        Action
1         Adult
2     Adventure
3     Animation
4     Biography
5        Comedy
6         Crime
7   Documentary
8         Drama
9        Family
10      Fantasy
11    Film-Noir
12    Game-Show
13      History
14       Horror
15        Music
16      Musical
17      Mystery
18         News
19   Reality-TV
20      Romance
21       Sci-Fi
22        Short
23        Sport
24    Talk-Show
25     Thriller
26          War
27      Western
28           \N

In [141]:
list(genres_uniq['0'])

['Action',
 'Adult',
 'Adventure',
 'Animation',
 'Biography',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Family',
 'Fantasy',
 'Film-Noir',
 'Game-Show',
 'History',
 'Horror',
 'Music',
 'Musical',
 'Mystery',
 'News',
 'Reality-TV',
 'Romance',
 'Sci-Fi',
 'Short',
 'Sport',
 'Talk-Show',
 'Thriller',
 'War',
 'Western',
 '\\N']

In [164]:
uniq_df = pd.DataFrame(columns=list(genres_uniq['0']) ,dtype=bool)

In [168]:
uniq_df.head()

Empty DataFrame
Columns: [Action, Adult, Adventure, Animation, Biography, Comedy, Crime, Documentary, Drama, Family, Fantasy, Film-Noir, Game-Show, History, Horror, Music, Musical, Mystery, News, Reality-TV, Romance, Sci-Fi, Short, Sport, Talk-Show, Thriller, War, Western, \N]
Index: []

[0 rows x 29 columns]

In [165]:
uniq_df.columns

Index(['Action', 'Adult', 'Adventure', 'Animation', 'Biography', 'Comedy',
       'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Film-Noir',
       'Game-Show', 'History', 'Horror', 'Music', 'Musical', 'Mystery', 'News',
       'Reality-TV', 'Romance', 'Sci-Fi', 'Short', 'Sport', 'Talk-Show',
       'Thriller', 'War', 'Western', '\N'],
      dtype='object')

In [169]:
genres

               genre0     genre1   genre2
1375654   Documentary      Short       \N
1375655   Documentary      Short       \N
1375656   Documentary      Short       \N
1375657   Documentary      Short       \N
1375658   Documentary      Short       \N
...               ...        ...      ...
19325260       Action  Adventure   Horror
19325265        Drama      Short       \N
19325276        Drama    Fantasy  Romance
19325281        Drama    Fantasy  Romance
19325291    Animation         \N       \N

[3611377 rows x 3 columns]

In [331]:
data_expanded = pd.concat([data ,uniq_df ,genres] ,axis=1)

In [332]:
data_expanded.head()

,ordering,region,language,types,attributes,isOriginalTitle,averageRating,numVotes,titleType,primaryTitle,...,Short,Sport,Talk-Show,Thriller,War,Western,\N,genre0,genre1,genre2
1375654,1,RS,\N,imdbDisplay,\N,True,7.0,1012.0,short,Passage de Venus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Documentary,Short,\N
1375655,5,CZ,\N,\N,\N,True,7.0,1012.0,short,Passage de Venus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Documentary,Short,\N
1375656,3,RU,\N,\N,\N,True,7.0,1012.0,short,Passage de Venus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Documentary,Short,\N
1375657,8,XWW,en,\N,informal literal English title,True,7.0,1012.0,short,Passage de Venus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Documentary,Short,\N
1375658,4,US,\N,imdbDisplay,\N,True,7.0,1012.0,short,Passage de Venus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Documentary,Short,\N

In [333]:
data_expanded.dtypes

ordering              int64
region               object
language             object
types                object
attributes           object
isOriginalTitle        bool
averageRating       float64
numVotes            float64
titleType            object
primaryTitle         object
originalTitle        object
isAdult                bool
startYear             int64
endYear               int64
runtimeMinutes        int64
genres               object
date_added            int64
yearsRun              int64
yearsToAdd            int64
runtime_cat        category
Action               object
Adult                object
Adventure            object
Animation            object
Biography            object
Comedy               object
Crime                object
Documentary          object
Drama                object
Family               object
Fantasy              object
Film-Noir            object
Game-Show            object
History              object
Horror               object
Music                object
Musical              object
Mystery              object
News                 object
Reality-TV           object
Romance              object
Sci-Fi               object
Short                object
Sport                object
Talk-Show            object
Thriller             object
War                  object
Western              object
\N                   object
genre0               object
genre1               object
genre2               object
dtype: object

In [334]:
def match_genre(x):
    return np.where((data_expanded.genre0[x.index] == x.name)
                    | (data_expanded.genre1[x.index] == x.name)
                    | (data_expanded.genre2[x.index] == x.name)
                    ,1 ,0)

In [335]:
data_expanded.region.unique()

array(['RS', 'CZ', 'RU', 'XWW', 'US', 'FR', 'CSHH', 'GB', '\\N', 'HU',
       'DE', 'PT', 'RO', 'GR', 'PL', 'FI', 'UY', 'IT', 'BR', 'ES', 'DK',
       'SE', 'AR', 'AU', 'TR', 'MX', 'SK', 'AT', 'XEU', 'VA', 'BE', 'CH',
       'IE', 'AZ', 'IN', 'SI', 'JP', 'NL', 'VE', 'NZ', 'NO', 'CO', 'UA',
       'IR', 'CA', 'BG', 'LI', 'MK', 'PY', 'CU', 'XYU', 'PA', 'ME', 'CL',
       'PE', 'ZA', 'XPI', 'PH', 'GE', 'SUHH', 'IL', 'LT', 'EE', 'BF',
       'DZ', 'DDDE', 'XWG', 'VN', 'IS', 'HR', 'BY', 'BA', 'EG', 'HK',
       'DO', 'TN', 'CN', 'YUCS', 'XSI', 'XKO', 'XSA', 'BO', 'PR', 'EC',
       'ID', 'BD', 'CR', 'LV', 'KR', 'SG', 'TW', 'HT', 'BUMM', 'PS', 'AD',
       'CM', 'MY', 'BJ', 'LU', 'AL', 'TH', 'GH', 'JM', 'PK', 'NG', 'XAS',
       'MA', 'MC', 'LB', 'SN', 'CG', 'GL', 'MN', 'KP', 'LK', 'GT', 'MZ',
       'BM', 'SD', 'MD', 'HN', 'LA', 'TM', 'KH', 'XAU', 'VDVN', 'GN',
       'NE', 'GA', 'CI', 'CY', 'MR', 'TD', 'NP', 'AM', 'TJ', 'SY', 'AF',
       nan, 'ZW', 'SV', 'BS', 'AO', 'MM', 'CD', 'TT', 'MT', 'BH', 'KW',
       'TG', 'KE', 'ML', 'EH', 'MG', 'SR', 'ET', 'GY', 'KG', 'UZ', 'LY',
       'MQ', 'IQ', 'MU', 'PG', 'CV', 'GW', 'BI', 'NI', 'ZM', 'CF', 'LS',
       'TZ', 'SO', 'FO', 'KZ', 'MO', 'GI', 'RW', 'SC', 'SM', 'DM', 'NC',
       'ZRCD', 'SA', 'BW', 'GP', 'MV', 'AE', 'JO', 'CSXX', 'PF', 'GU',
       'SL', 'AW', 'BT', 'TO', 'KM', 'XKV', 'AG', 'YE', 'ER', 'UG', 'AN',
       'IM', 'SZ', 'BB', 'MS', 'BZ', 'NU', 'ST', 'VI', 'QA', 'GD', 'OM',
       'FJ', 'NR', 'VU', 'GQ', 'LR', 'VC', 'TL', 'LC', 'MW', 'AQ', 'RE',
       'MH', 'GM', 'KN', 'GF', 'SB', 'SH', 'WS', 'TV', 'KY', 'BN', 'PW',
       'AS', 'CK', 'VG', 'XNA', 'AI'], dtype=object)

In [198]:
#exploratory code
data_expanded.groupby('region').apply(lambda x: x.region=='US').agg('sum')

565559

In [283]:
data_expanded.loc[data_expanded.runtime_cat.isnull()]

,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,...,originalTitle,primaryTitle,region,runtimeMinutes,runtime_cat,startYear,titleType,types,yearsRun,yearsToAdd
1376740,False,False,False,False,False,False,False,False,False,False,...,Rip's Twenty Years' Sleep,Rip's Twenty Years' Sleep,US,0.0,NaN,1896.0,short,\N,0.0,0.0
1377055,False,False,False,False,False,False,False,False,False,False,...,Awakening of Rip,Awakening of Rip,US,0.0,NaN,1896.0,short,\N,0.0,0.0
1507459,False,False,False,False,False,False,False,False,False,False,...,Concerning $1000,Concerning $1000,US,0.0,NaN,1916.0,short,\N,0.0,0.0
8615210,False,False,False,False,False,False,False,False,False,False,...,The Talk,The Talk,US,0.0,NaN,2003.0,short,\N,0.0,0.0
9261013,False,False,False,False,False,False,False,False,False,False,...,The Last Flight,The Last Flight,US,0.0,NaN,2005.0,short,\N,0.0,0.0
9860302,False,False,False,False,False,False,False,False,False,False,...,V-r,V-r,US,0.0,NaN,2006.0,short,\N,0.0,0.0

In [287]:
#maybe don't do this
#data_expanded = data_expanded.loc[data_expanded.region=='US']

In [2]:
data_expanded = data_expanded.apply(lambda x: match_genre(x) 
                                    if x.name in uniq_df.columns else x ,axis='index')

NameError: name 'data_expanded' is not defined

In [201]:
data_expanded.head()

,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,...,originalTitle,primaryTitle,region,runtimeMinutes,runtime_cat,startYear,titleType,types,yearsRun,yearsToAdd
1375658,0,0,0,0,0,0,0,0,0,0,...,Passage de Venus,Passage de Venus,US,1.0,0-30,1874.0,short,imdbDisplay,0.0,0.0
1375663,0,0,0,0,0,0,0,0,0,0,...,Sallie Gardner at a Gallop,Sallie Gardner at a Gallop,US,1.0,0-30,1878.0,short,alternative,0.0,0.0
1375666,0,0,0,0,0,0,0,0,0,0,...,Sallie Gardner at a Gallop,Sallie Gardner at a Gallop,US,1.0,0-30,1878.0,short,\N,0.0,0.0
1375669,0,0,0,0,0,0,0,0,0,0,...,Buffalo Running,Buffalo Running,US,1.0,0-30,1883.0,short,\N,0.0,0.0
1375673,0,0,0,0,0,0,0,0,0,0,...,Boys Playing Leapfrog: Side View,Jumping Over a Man's Back-Leapfrog,US,1.0,0-30,1887.0,short,\N,0.0,0.0

In [2528]:
#exploratory code
data_sorted.genres.loc[data_sorted.genres.str.contains('Comedy') & data_sorted.genres.str.contains('Romance')].unique()

array(['Comedy,Romance', 'Comedy,Drama,Romance', 'Comedy,Musical,Romance',
       'Comedy,Crime,Romance', 'Comedy,Family,Romance',
       'Comedy,Fantasy,Romance', 'Comedy,Romance,Sport',
       'Comedy,Romance,Short', 'Animation,Comedy,Romance',
       'Adult,Comedy,Romance', 'Action,Comedy,Romance',
       'Comedy,Horror,Romance', 'Comedy,Romance,Sci-Fi'], dtype=object)

In [202]:
data.shape

(3611377, 20)

In [337]:
data_expanded.shape

(3611377, 52)

In [369]:
data_expanded.dtypes

ordering              int64
region               object
language           category
types                object
attributes           object
isOriginalTitle        bool
averageRating       float64
numVotes            float64
titleType            object
primaryTitle         object
originalTitle        object
isAdult                bool
startYear             int64
endYear               int64
runtimeMinutes        int64
genres               object
date_added            int64
yearsRun              int64
yearsToAdd            int64
runtime_cat        category
Action                 bool
Adult                  bool
Adventure              bool
Animation              bool
Biography              bool
Comedy                 bool
Crime                  bool
Documentary            bool
Drama                  bool
Family                 bool
Fantasy                bool
Film-Noir              bool
Game-Show              bool
History                bool
Horror                 bool
Music                  bool
Musical                bool
Mystery                bool
News                   bool
Reality-TV             bool
Romance                bool
Sci-Fi                 bool
Short                  bool
Sport                  bool
Talk-Show              bool
Thriller               bool
War                    bool
Western                bool
\N                     bool
genre0               object
genre1               object
genre2               object
dtype: object

In [339]:
data_bool = list(genres_uniq['0']) + ['isAdult','isOriginalTitle']

In [340]:
data_expanded[data_bool] = data_expanded[data_bool].astype('bool')

In [473]:
data_cat = ['language','runtime_cat','titleType','region']

In [474]:
data_expanded[data_cat] = data_expanded[data_cat].astype('category')

In [475]:
data_obj = list(data_expanded.columns[data_expanded.dtypes==np.object])

In [408]:
data_time = ['date_added']#,'endYear','runtimeMinutes','startYear']

In [476]:
data_obj

['types',
 'attributes',
 'primaryTitle',
 'originalTitle',
 'genres',
 'genre0',
 'genre1',
 'genre2']

In [477]:
data_time

['date_added']

In [478]:
data_sorted = data_expanded.loc[data_expanded.date_added!=0]

In [479]:
data_sorted = data_sorted.drop(columns=data_obj+data_time+['ordering'])

In [480]:
data_sorted = data_sorted.loc[data_sorted.yearsToAdd!=0]

In [481]:
data_num = list(data_sorted.columns[(data_sorted.dtypes==np.float64) | (data_sorted.dtypes==np.int64)])

In [482]:
data_sorted.shape

(31962, 42)

In [483]:
data_sorted.describe()

,averageRating,numVotes,startYear,endYear,runtimeMinutes,yearsRun,yearsToAdd
count,23899.000000,2.389900e+04,31962.000000,31962.000000,31962.000000,31962.000000,31962.000000
mean,6.736964,4.750501e+04,2003.337526,149.549277,67.350416,0.217164,14.799950
std,1.262809,1.441237e+05,18.496925,527.262948,60.780927,1.087310,18.545716
min,1.000000,5.000000e+00,1896.000000,0.000000,1.000000,0.000000,-9.000000
25%,6.000000,9.400000e+01,2001.000000,0.000000,22.000000,0.000000,3.000000
50%,6.900000,1.293000e+03,2010.000000,0.000000,62.000000,0.000000,8.000000
75%,7.700000,2.174300e+04,2015.000000,0.000000,100.000000,0.000000,18.000000
max,10.000000,1.892958e+06,2021.000000,2019.000000,3900.000000,34.000000,124.000000

In [484]:
data_sorted.dtypes

region             category
language           category
isOriginalTitle        bool
averageRating       float64
numVotes            float64
titleType          category
isAdult                bool
startYear             int64
endYear               int64
runtimeMinutes        int64
yearsRun              int64
yearsToAdd            int64
runtime_cat        category
Action                 bool
Adult                  bool
Adventure              bool
Animation              bool
Biography              bool
Comedy                 bool
Crime                  bool
Documentary            bool
Drama                  bool
Family                 bool
Fantasy                bool
Film-Noir              bool
Game-Show              bool
History                bool
Horror                 bool
Music                  bool
Musical                bool
Mystery                bool
News                   bool
Reality-TV             bool
Romance                bool
Sci-Fi                 bool
Short                  bool
Sport                  bool
Talk-Show              bool
Thriller               bool
War                    bool
Western                bool
\N                     bool
dtype: object

In [485]:
data_sorted = data_sorted.loc[data_sorted.groupby(['language'])['language'].filter(lambda x: x.count()>1).index]

In [455]:
'''for x in range(len(data.columns)):
    with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
        print (data.columns[x] ,'\n' ,data.iloc[:,x].notnull().value_counts())'''

region
 True    36159
Name: region, dtype: int64
language
 True    36159
Name: language, dtype: int64
types
 True    36159
Name: types, dtype: int64
isOriginalTitle
 True    36159
Name: isOriginalTitle, dtype: int64
averageRating
 True     27746
False     8413
Name: averageRating, dtype: int64
numVotes
 True     27746
False     8413
Name: numVotes, dtype: int64
titleType
 True    36159
Name: titleType, dtype: int64
isAdult
 True    36159
Name: isAdult, dtype: int64
runtimeMinutes
 True    36159
Name: runtimeMinutes, dtype: int64
genres
 True    36159
Name: genres, dtype: int64
yearsRun
 True    36159
Name: yearsRun, dtype: int64
yearsToAdd
 True    36159
Name: yearsToAdd, dtype: int64

In [249]:
#dataset = dataset.reset_index()

In [357]:
from sklearn.model_selection import StratifiedShuffleSplit

In [486]:
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(data_sorted, data_sorted[['language']]):                               
    strat_train_set = data_sorted.iloc[train_index]
    strat_test_set = data_sorted.iloc[test_index]

In [487]:
datatrain = strat_train_set.copy()

In [488]:
xset = datatrain.drop(columns=['yearsToAdd'])

In [489]:
yset = datatrain['yearsToAdd'].copy()

In [251]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [1556]:
#data_cat_exclude = data_num.copy()

In [1557]:
#data_cat_exclude.extend(['isOriginalTitle','isAdult'])

In [400]:
#del data_cat_exclude

In [ ]:
#data_num.remove(['date_added', 'primaryTitle'])

In [1558]:
#data_cat = list(xset.drop(columns=data_cat_exclude))

In [490]:
data_num

['averageRating',
 'numVotes',
 'startYear',
 'endYear',
 'runtimeMinutes',
 'yearsRun',
 'yearsToAdd']

In [491]:
data_cat

['language', 'runtime_cat', 'titleType', 'region']

In [253]:
num_pipeline = Pipeline([
    ('imputer' ,SimpleImputer(strategy='mean')),
    ('std_scaler' ,StandardScaler()),
])

In [254]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [270]:
xset.head()

,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,...,War,Western,\N,averageRating,isAdult,isOriginalTitle,language,numVotes,runtime_cat,yearsRun
1650377,False,False,False,False,False,False,False,False,False,False,...,False,False,False,6.9,False,True,\N,96.0,0-30,0.0
6894425,False,False,False,False,False,False,False,False,False,False,...,False,False,False,5.8,False,False,\N,40.0,60-90,0.0
15780522,False,False,False,False,False,False,False,False,False,False,...,False,False,False,8.0,False,True,\N,23128.0,0-30,0.0
9401594,False,False,False,False,False,False,False,False,False,False,...,False,False,False,6.8,True,True,\N,32.0,60-90,0.0
16730560,False,False,False,False,False,False,False,False,False,False,...,False,False,False,NaN,False,True,\N,NaN,0-30,0.0

In [1009]:
yset.iloc[:5]

11997040     2
11445115     0
11639359     1
12159697     6
1603867     14
Name: yearsToAdd, dtype: int64

In [ ]:
#plot the yset

In [650]:
'''xvals = xvals.loc[xvals.date_added.notna() & xvals.startYear.notna()]
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1)

ax.plot(xsetYearsToAdd, ysetStart,
       'r-', lw=5, alpha=0.6, label='yset')

ax.hist(r, density=True, histtype='stepfilled', alpha=0.2)
ax.legend(loc='best', frameon=False)
plt.show()'''

In [493]:
data_num[:-1]

['averageRating',
 'numVotes',
 'startYear',
 'endYear',
 'runtimeMinutes',
 'yearsRun']

In [522]:
np.array(data_cat)[[0,2,3]]

array(['language', 'titleType', 'region'], dtype='<U11')

In [521]:
data_cat[1]

'runtime_cat'

In [523]:
full_pipeline = ColumnTransformer([
    ('num' ,num_pipeline ,data_num[:-1]),
    ('cat1',OneHotEncoder() ,np.array(data_cat)[[0,2,3]]),
   ('cat',OrdinalEncoder() ,[data_cat[1]]),
])

In [524]:
data_prepped = full_pipeline.fit_transform(xset)

In [525]:
data_prepped

<25563x176 sparse matrix of type '<class 'numpy.float64'>'
	with 240631 stored elements in Compressed Sparse Row format>

In [322]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print (xset)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [526]:
xset.shape

(25563, 41)

In [527]:
yset[yset<0]

16883015   -1
18364019   -2
19286999   -4
17176287   -1
19104760   -1
           ..
16849086   -2
19310976   -1
18882771   -2
18022719   -1
17433802   -2
Name: yearsToAdd, Length: 480, dtype: int64

In [528]:
data_prepped

<25563x176 sparse matrix of type '<class 'numpy.float64'>'
	with 240631 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.linear_model import LinearRegression

In [529]:
lin_reg = LinearRegression()
lin_reg.fit(data_prepped, yset)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [530]:
some_data = xset.iloc[:5]
some_labels = yset.iloc[:5]
some_data_prepared = full_pipeline.transform(some_data)
print("Predictions:", lin_reg.predict(some_data_prepared))
print("Labels:", some_labels)

Predictions: [ 7.60664629  0.09071208  8.10697928  1.07407033 10.17204614]
Labels: 12566411    7
18441927    1
12114967    8
17398459    1
11114654    8
Name: yearsToAdd, dtype: int64

In [531]:
from sklearn.metrics import mean_squared_error

In [532]:
linreg_predictions = lin_reg.predict(data_prepped)
lin_mse = mean_squared_error(yset, linreg_predictions)
lin_rmse = np.sqrt(lin_mse)
lin_rmse #=1.1006214426324143

1.1006214426324143

In [533]:
(lin_reg.predict(data_prepped)==yset).value_counts()

False    25563
Name: yearsToAdd, dtype: int64

In [534]:
from sklearn.model_selection import cross_val_score

In [535]:
scores = cross_val_score(lin_reg, data_prepped, yset
                         , scoring="neg_mean_squared_error", cv=10)
lin_reg_rmse_scores = np.sqrt(-scores)

In [536]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())
    
display_scores(lin_reg_rmse_scores)

Scores: [1.12199208 1.09104215 1.12360598 1.0737641  1.1053581  1.10875544
 1.14707456 1.06332323 1.127913   1.12068833]
Mean: 1.1083516968172908
Standard deviation: 0.024465607409508507

In [ ]:
#figure out what LinearRegression parameters are for GridSearchCV

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [537]:
tree_reg = DecisionTreeRegressor()
tree_reg.fit(data_prepped, yset)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [538]:
tree_predictions = tree_reg.predict(data_prepped)
tree_mse = mean_squared_error(yset, tree_predictions)
tree_rmse = np.sqrt(tree_mse)
tree_rmse #=0.48413151619014866

0.3881645206012715

In [539]:
some_data = xset.iloc[:5]
some_labels = yset.iloc[:5]
some_data_prepared = full_pipeline.transform(some_data)
print("Predictions:", tree_reg.predict(some_data_prepared))
print("Labels:", some_labels)

Predictions: [7.  1.  8.2 1.  9. ]
Labels: 12566411    7
18441927    1
12114967    8
17398459    1
11114654    8
Name: yearsToAdd, dtype: int64

In [540]:
(tree_reg.predict(data_prepped)==yset).value_counts()

True     21381
False     4182
Name: yearsToAdd, dtype: int64

In [541]:
from sklearn.model_selection import cross_val_score

In [542]:
scores = cross_val_score(tree_reg, data_prepped, yset
                         ,scoring="neg_mean_squared_error", cv=10)
tree_rmse_scores = np.sqrt(-scores)

In [543]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())
    
display_scores(tree_rmse_scores)

Scores: [1.17663533 1.10370578 1.21640872 1.17343967 1.18492144 1.15763673
 1.19223979 1.10223432 1.19945382 1.16266491]
Mean: 1.1669340514347168
Standard deviation: 0.03590846537636253

In [544]:
data_prepped

<25563x176 sparse matrix of type '<class 'numpy.float64'>'
	with 240631 stored elements in Compressed Sparse Row format>

In [398]:
from sklearn.model_selection import GridSearchCV

In [561]:
param_grid = [
    {'random_state': [39], 'max_features': [154,155,156]},
   # {'random_state': 42, 'max_features': [100 ,530]},
]
#tree_reg = DecisionTreeRegressor()
grid_search = GridSearchCV(tree_reg, param_grid, cv=5,
                          scoring = 'neg_mean_squared_error',
                          return_train_score = True,
                          verbose=2, n_jobs=4)
grid_search.fit(data_prepped, yset)

Fitting 5 folds for each of 3 candidates, totalling 15 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  15 out of  15 | elapsed:    3.9s finished

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=DecisionTreeRegressor(criterion='mse', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort=False, random_state=None,
                                             splitter='best'),
             iid='warn', n_jobs=4,
             param_grid=[{'max_features': [154, 155, 156],
                          'random_state': [39]}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='neg_mean_squared_error', verbose=2)

In [562]:
grid_search.best_params_

{'max_features': 155, 'random_state': 39}

In [563]:
grid_search.best_estimator_

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=155,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=39, splitter='best')

In [564]:
#do not run this, compare with future runs
cvres = grid_search.cv_results_
for mean_score, params in zip(cvres["mean_test_score"], cvres["params"]):
    print(np.sqrt(-mean_score), params)

1.200447441307155 {'max_features': 154, 'random_state': 39}
1.1886083987134977 {'max_features': 155, 'random_state': 39}
1.1907052242085503 {'max_features': 156, 'random_state': 39}

In [ ]:
#for saving RMSE scores

In [565]:
negative_mse = grid_search.best_score_
rmse = np.sqrt(-negative_mse)
rmse #=1.1886083987134977

1.1886083987134977

In [446]:
tree_reg = grid_search.best_estimator_

X_test = strat_test_set.drop("yearsToAdd", axis=1)
y_test = strat_test_set["yearsToAdd"].copy()

X_test_prepared = full_pipeline.transform(X_test)

final_predictions = tree_reg.predict(X_test_prepared)

final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)
final_rmse #=1.0330039931551116

1.0330039931551116

In [1340]:
from sklearn.svm import SVR

SVR = SVR()
SVR.fit(data_prepped, yset)

/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [1341]:
SVR_predictions = SVR_reg.predict(data_prepped)
SVR_mse = mean_squared_error(yset, SVR_predictions)
SVR_rmse = np.sqrt(tree_mse)
SVR_rmse #=0.0 (after stratifysplit by region)

0.0

In [1342]:
#takes a long time to run
scores = cross_val_score(SVR, data_prepped, yset
                         , scoring="neg_mean_squared_error", cv=10)
SVR_rmse_scores = np.sqrt(-scores)
display_scores(SVR_rmse_scores)

/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

Scores: [0.26919902 0.31610469 0.29779647 0.28090404 0.25620059 0.32514427
 0.30124398 0.27280085 0.31322774 0.36748575]
Mean: 0.3000107406781623
Standard deviation: 0.0309819859168431

In [1343]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())
    
display_scores(SVR_rmse_scores)

Scores: [0.26919902 0.31610469 0.29779647 0.28090404 0.25620059 0.32514427
 0.30124398 0.27280085 0.31322774 0.36748575]
Mean: 0.3000107406781623
Standard deviation: 0.0309819859168431

In [1344]:
param_grid = [
    {'kernel': ["linear"], 'C': [20 ,40] ,'gamma': [50 ,200]},
  #  {'kernel': ["rbf"], 'C': [70 ,90] ,'gamma': [.1 ,.3]},
]
#SVR = SVR()
grid_search = GridSearchCV(SVR, param_grid, cv=5,
                          scoring = 'neg_mean_squared_error',
                          return_train_score = True,
                          verbose=2, n_jobs=4)
grid_search.fit(data_prepped, yset)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed: 12.8min
[Parallel(n_jobs=4)]: Done  40 out of  40 | elapsed: 19.4min finished

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3,
                           epsilon=0.1, gamma='auto_deprecated', kernel='rbf',
                           max_iter=-1, shrinking=True, tol=0.001,
                           verbose=False),
             iid='warn', n_jobs=4,
             param_grid=[{'C': [20, 50], 'gamma': [50, 200],
                          'kernel': ['linear']},
                         {'C': [70, 90], 'gamma': [0.1, 0.3],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='neg_mean_squared_error', verbose=2)

In [1345]:
grid_search.best_params_

{'C': 20, 'gamma': 50, 'kernel': 'linear'}

In [1346]:
grid_search.best_estimator_

SVR(C=20, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=50,
    kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [1347]:
#do not run this, compare with future runs
cvres = grid_search.cv_results_
for mean_score, params in zip(cvres["mean_test_score"], cvres["params"]):
    print(np.sqrt(-mean_score), params)

0.073830596240395 {'C': 20, 'gamma': 50, 'kernel': 'linear'}
0.073830596240395 {'C': 20, 'gamma': 200, 'kernel': 'linear'}
0.073830596240395 {'C': 50, 'gamma': 50, 'kernel': 'linear'}
0.073830596240395 {'C': 50, 'gamma': 200, 'kernel': 'linear'}
0.5683748025178127 {'C': 70, 'gamma': 0.1, 'kernel': 'rbf'}
1.7336933921846571 {'C': 70, 'gamma': 0.3, 'kernel': 'rbf'}
0.5660870190803804 {'C': 90, 'gamma': 0.1, 'kernel': 'rbf'}
1.7306255422484251 {'C': 90, 'gamma': 0.3, 'kernel': 'rbf'}

In [1348]:
negative_mse = grid_search.best_score_
rmse = np.sqrt(-negative_mse)
rmse

0.073830596240395

In [1349]:
SVR = grid_search.best_estimator_

X_test = strat_test_set.drop("yearsToAdd", axis=1)
y_test = strat_test_set["yearsToAdd"].copy()

X_test_prepared = full_pipeline.transform(X_test)

final_predictions = SVR.predict(X_test_prepared)

final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)
final_rmse #=0.07368869765316144

0.07368869765316144

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [566]:
forest_reg = RandomForestRegressor()
forest_reg.fit(data_prepped, yset)

/Volumes/lin/MachineLearning/env/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [567]:
forest_predictions = forest_reg.predict(data_prepped)
forest_mse = mean_squared_error(yset, forest_predictions)
forest_rmse = np.sqrt(forest_mse)
forest_rmse #=0.5262934207002237

0.5262934207002237

In [568]:
#takes a long time to run
scores = cross_val_score(forest_reg, data_prepped, yset
                         , scoring="neg_mean_squared_error", cv=10)
forest_rmse_scores = np.sqrt(-scores)
display_scores(forest_rmse_scores)

Scores: [1.00842366 0.95862721 1.02614449 0.97726958 0.99418985 0.99738024
 1.04190676 0.93471419 0.99729176 1.00568093]
Mean: 0.9941628674901477
Standard deviation: 0.029564831518092555

In [569]:
data_prepped

<25563x176 sparse matrix of type '<class 'numpy.float64'>'
	with 240631 stored elements in Compressed Sparse Row format>

In [571]:
param_grid = [
  #  {'n_estimators': [50 ,100], 'max_features': [635 ,636]},
    {'bootstrap': [False], 'n_estimators': [20,40], 'max_features': [146,155,161] ,'random_state':[42]},
]
#forest_reg = RandomForestRegressor()
grid_search = GridSearchCV(forest_reg, param_grid, cv=5,
                          scoring = 'neg_mean_squared_error',
                          return_train_score = True)
grid_search.fit(data_prepped, yset)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestRegressor(bootstrap=True, criterion='mse',
                                             max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=10, n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid=[{'bootstrap': [False], 'max_features': [146, 155, 161],
                          'n_estimators': [20, 40], 'random_state': [42]}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='neg_mean_squared_error', verbose=0)

In [572]:
grid_search.best_params_

{'bootstrap': False,
 'max_features': 146,
 'n_estimators': 40,
 'random_state': 42}

In [573]:
grid_search.best_estimator_

RandomForestRegressor(bootstrap=False, criterion='mse', max_depth=None,
                      max_features=146, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=40,
                      n_jobs=None, oob_score=False, random_state=42, verbose=0,
                      warm_start=False)

In [574]:
cvres = grid_search.cv_results_
for mean_score, params in zip(cvres["mean_test_score"], cvres["params"]):
    print(np.sqrt(-mean_score), params)

1.0265414663437407 {'bootstrap': False, 'max_features': 146, 'n_estimators': 20, 'random_state': 42}
1.0216609176636444 {'bootstrap': False, 'max_features': 146, 'n_estimators': 40, 'random_state': 42}
1.0443506425066893 {'bootstrap': False, 'max_features': 155, 'n_estimators': 20, 'random_state': 42}
1.0392965149648767 {'bootstrap': False, 'max_features': 155, 'n_estimators': 40, 'random_state': 42}
1.060351446585804 {'bootstrap': False, 'max_features': 161, 'n_estimators': 20, 'random_state': 42}
1.0589375404459298 {'bootstrap': False, 'max_features': 161, 'n_estimators': 40, 'random_state': 42}

In [575]:
cat_encoder =

array([ 7.60484955e-04,  2.42486533e-03,  9.82195250e-01,  1.15639961e-03,
        1.09269286e-02,  1.70715919e-04,  1.53395674e-05,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  3.00435201e-08,  2.36653795e-10,
        0.00000000e+00,  1.68448649e-05,  1.59974603e-07,  1.58941197e-08,
        1.43562571e-06,  3.10667142e-08,  1.30023881e-06,  3.78646073e-10,
        2.36653795e-09,  3.58055979e-08,  1.75931095e-08,  0.00000000e+00,
        2.26878965e-09,  1.62498175e-08,  3.78646073e-09,  1.89323036e-09,
        1.03382340e-07,  1.00698089e-07,  0.00000000e+00,  1.76138039e-08,
        1.19459256e-06,  1.48374132e-03,  5.05848609e-05,  8.73037040e-05,
        9.03550585e-06,  2.72495846e-05,  4.02015217e-05,  5.87975356e-06,
        4.13104346e-06,  2.43872845e-05,  8.07998908e-07, -1.00891581e-22,
        6.00364785e-07,  4.86694252e-06,  2.27540493e-06,  2.03697307e-05,
        0.00000000e+00, -2.62318111e-22,  5.82003170e-07,  2.28603520e-08,
        2.66764071e-07,  3.88155078e-06,  1.12262236e-06,  3.95002304e-07,
        2.34683023e-08,  4.73083669e-06,  3.90672864e-07,  3.13047956e-07,
        2.08675880e-05,  8.70300541e-07,  1.34785912e-06,  1.26884067e-06,
        6.63140291e-07,  9.05062463e-09,  5.70977688e-08,  1.78130925e-07,
        1.95316736e-07,  1.47074419e-07,  7.36922526e-07,  1.53728663e-07,
        1.11669547e-05,  4.10912955e-06,  1.23406157e-07,  8.62983988e-08,
        4.15579152e-07,  2.76773832e-07,  9.50752989e-06,  8.41075080e-09,
        3.07795435e-06,  5.15909231e-07,  1.43334150e-05,  3.46931333e-05,
        3.54586782e-08,  2.25277055e-08,  1.39417692e-08,  4.22740252e-06,
        1.82561499e-09,  2.88551767e-06,  6.37734525e-07,  1.14091754e-06,
        1.95558809e-06,  4.34995163e-06,  1.28255946e-06,  2.06754497e-05,
        4.66685287e-07,  2.35808193e-06,  2.73842085e-07,  9.95344543e-06,
        1.08184592e-09,  1.04826561e-06,  7.98782158e-06,  4.07486556e-07,
        0.00000000e+00,  9.90767624e-08,  3.40966245e-06,  2.84793076e-08,
        5.10889075e-07,  3.78215793e-09,  0.00000000e+00,  1.68770679e-07,
        1.99933577e-07,  4.58157338e-08,  0.00000000e+00,  8.40454418e-07,
        1.22347810e-07,  1.99921891e-07,  7.80957525e-09,  1.13133683e-06,
        4.65547885e-06,  1.07969424e-06,  0.00000000e+00,  4.80085797e-07,
        3.13656356e-06,  3.60294583e-06,  1.49841423e-07,  4.41762917e-06,
        8.51953663e-10,  1.03786421e-07,  3.49607374e-06,  1.12762973e-06,
        2.19056158e-06,  2.97690999e-07,  4.36534110e-08,  2.89512964e-06,
        6.16504175e-08,  2.31398001e-07,  1.43978544e-06,  6.05459691e-07,
        2.09363851e-06,  2.87772258e-08,  3.74481462e-08,  0.00000000e+00,
        7.04234683e-06,  3.74622729e-06,  3.95951424e-07,  3.75586002e-07,
        4.18258520e-08,  0.00000000e+00, -7.74847343e-21,  5.20638350e-09,
        8.72946055e-08,  4.45839032e-07,  8.44996354e-09,  2.96514235e-06,
        3.60727524e-08,  3.27977489e-08,  4.32904983e-06,  9.65195384e-06,
        6.34192320e-07,  5.03524565e-05,  7.00938529e-07,  1.08962908e-21,
        2.12272870e-07,  3.90872714e-07,  1.41567933e-08,  3.39253920e-06,
        2.09522497e-07,  3.87863586e-05,  2.26590205e-05,  3.53115150e-08,
        0.00000000e+00,  2.25238429e-06,  2.57763894e-05,  1.77478599e-04])

In [577]:
#extra_attribs = ["rooms_per_hhold", "pop_per_hhold", "bedrooms_per_room"]
cat1_encoder = full_pipeline.named_transformers_["cat1"]
cat1 = list(cat1_encoder.categories_[0])
cat_encoder = full_pipeline.named_transformers_["cat"]
cat = list(cat_encoder.categories_[0])
attributes = cat + cat1 + list(data_sorted.columns)
sorted(zip(feature_importances, attributes), reverse = True)

[(0.9821952496927612, '30-60'),
 (0.010926928571310736, '90-120'),
 (0.0024248653270420085, '120-180'),
 (0.0014837413152843837, 'region'),
 (0.0011563996074282273, '60-90'),
 (0.0007604849547176488, '0-30'),
 (0.00017071591867756509, 'Long'),
 (8.730370401160715e-05, 'isOriginalTitle'),
 (5.0584860908992114e-05, 'language'),
 (4.020152170903609e-05, 'titleType'),
 (2.7249584612051578e-05, 'numVotes'),
 (2.438728448221613e-05, 'endYear'),
 (2.0867587962429278e-05, 'Horror'),
 (2.036973074979366e-05, 'Adult'),
 (1.6844864944116266e-05, 'en'),
 (1.5339567390265586e-05, '\\N'),
 (1.1166954678697201e-05, 'War'),
 (9.035505847010957e-06, 'averageRating'),
 (5.879753560390982e-06, 'isAdult'),
 (4.866942517307497e-06, 'runtime_cat'),
 (4.730836692041803e-06, 'Film-Noir'),
 (4.13104346346876e-06, 'startYear'),
 (4.109129551455079e-06, 'Western'),
 (3.881550779306143e-06, 'Documentary'),
 (2.275404925386289e-06, 'Action'),
 (1.4356257104891647e-06, 'fr'),
 (1.3478591194128094e-06, 'Musical'),
 (1.3002388114374063e-06, 'hi'),
 (1.26884066861376e-06, 'Mystery'),
 (1.1945925593543708e-06, 'tr'),
 (1.1226223591507043e-06, 'Drama'),
 (8.70300540615582e-07, 'Music'),
 (8.079989078600146e-07, 'runtimeMinutes'),
 (7.369225264762675e-07, 'Talk-Show'),
 (6.631402905376772e-07, 'News'),
 (6.0036478504932e-07, 'yearsToAdd'),
 (5.820031700483074e-07, 'Biography'),
 (3.9500230429597605e-07, 'Family'),
 (3.906728638753934e-07, 'Game-Show'),
 (3.130479555813783e-07, 'History'),
 (2.6676407087036657e-07, 'Crime'),
 (1.953167359961616e-07, 'Short'),
 (1.7813092472840594e-07, 'Sci-Fi'),
 (1.5997460252163477e-07, 'es'),
 (1.5372866315392538e-07, 'Thriller'),
 (1.4707441940532157e-07, 'Sport'),
 (1.2340615742012358e-07, '\\N'),
 (1.0338233957339382e-07, 'sr'),
 (1.0069808934907842e-07, 'sv'),
 (5.709776877414516e-08, 'Romance'),
 (3.5805597883085664e-08, 'ml'),
 (3.1066714228369556e-08, 'he'),
 (3.0043520148566284e-08, 'cmn'),
 (2.346830233861041e-08, 'Fantasy'),
 (2.2860351982020082e-08, 'Comedy'),
 (1.7613803914780295e-08, 'te'),
 (1.7593109513618974e-08, 'mr'),
 (1.6249817494013555e-08, 'qbp'),
 (1.5894119668199534e-08, 'fa'),
 (9.05062463239056e-09, 'Reality-TV'),
 (3.786460726367686e-09, 'ru'),
 (2.366537954000023e-09, 'id'),
 (2.2687896472532486e-09, 'qbn'),
 (1.8932303632025687e-09, 'sl'),
 (3.7864607263715607e-10, 'hr'),
 (2.3665379536561466e-10, 'cs'),
 (0.0, 'ta'),
 (0.0, 'nl'),
 (0.0, 'de'),
 (0.0, 'ca'),
 (0.0, 'bg'),
 (0.0, 'ar'),
 (0.0, 'Adventure'),
 (-1.0089158112693843e-22, 'yearsRun'),
 (-2.623181109300402e-22, 'Animation')]

In [578]:
forest_reg = grid_search.best_estimator_

X_test = strat_test_set.drop("yearsToAdd", axis=1)
y_test = strat_test_set["yearsToAdd"].copy()

X_test_prepared = full_pipeline.transform(X_test)

final_predictions = forest_reg.predict(X_test_prepared)

final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)#=> evaluates to 47,730.2
final_rmse #0.13444384334475334

ValueError: Found unknown categories ['BO', 'LS', 'AF', 'SZ'] in column 2 during transform

In [1619]:
#seems to only work for numerical datasets
from sklearn.decomposition import PCA

In [1620]:
pca = PCA(n_components=.95)
base_reduced = pca.fit_transform(xset)

ValueError: could not convert string to float: 'US'

In [462]:
data_sorted.shape

(31954, 40)

In [463]:
data_sorted.columns

Index(['language', 'isOriginalTitle', 'averageRating', 'numVotes', 'isAdult',
       'startYear', 'endYear', 'runtimeMinutes', 'yearsRun', 'yearsToAdd',
       'runtime_cat', 'Action', 'Adult', 'Adventure', 'Animation', 'Biography',
       'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy',
       'Film-Noir', 'Game-Show', 'History', 'Horror', 'Music', 'Musical',
       'Mystery', 'News', 'Reality-TV', 'Romance', 'Sci-Fi', 'Short', 'Sport',
       'Talk-Show', 'Thriller', 'War', 'Western', '\N'],
      dtype='object')

In [579]:
data_new = data_expanded[data_sorted.columns].drop(columns='yearsToAdd')

In [466]:
data_new.shape

(3611377, 39)

In [580]:
data_new = data_new.loc[(data_new.startYear>2018)
                       & (data_new.region == 'US')
                     #  & (data_new.genres.isin(list(data_sorted.genres)))
                       & (data_new.titleType.isin(['movie']))]

In [582]:
some_new = data_new.sample(n=1000)

In [583]:
some_new.head()

,region,language,isOriginalTitle,averageRating,numVotes,titleType,isAdult,startYear,endYear,runtimeMinutes,...,Reality-TV,Romance,Sci-Fi,Short,Sport,Talk-Show,Thriller,War,Western,\N
19137023,US,\N,False,NaN,NaN,movie,False,2019,0,72,...,False,False,False,False,False,False,False,False,False,True
19187048,US,\N,True,NaN,NaN,movie,False,2019,0,180,...,False,False,False,False,False,False,False,False,False,True
18987424,US,\N,False,8.3,21.0,movie,False,2019,0,99,...,False,False,False,False,False,False,False,False,False,True
18941785,US,en,True,6.6,57454.0,movie,False,2019,0,110,...,False,False,False,False,False,False,False,False,False,False
18771466,US,\N,True,9.4,16.0,movie,False,2019,0,75,...,False,False,False,False,True,False,False,False,False,False

In [584]:
data.shape

(3611377, 20)

In [585]:
data.loc[some_new.index]

,ordering,region,language,types,attributes,isOriginalTitle,averageRating,numVotes,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,date_added,yearsRun,yearsToAdd,runtime_cat
19137023,1,US,\N,\N,\N,False,NaN,NaN,movie,Agent X the movie,Agent X the movie,False,2019,0,72,Mystery,0,0,0,60-90
19187048,1,US,\N,imdbDisplay,\N,True,NaN,NaN,movie,Present Laughter,Present Laughter,False,2019,0,180,Comedy,0,0,0,120-180
18987424,1,US,\N,imdbDisplay,\N,False,8.3,21.0,movie,Watson,Watson,False,2019,0,99,Documentary,0,0,0,90-120
18941785,5,US,en,\N,\N,True,6.6,57454.0,movie,"Extremely Wicked, Shockingly Evil and Vile","Extremely Wicked, Shockingly Evil and Vile",False,2019,0,110,"Biography,Crime,Drama",2019,0,0,90-120
18771466,1,US,\N,\N,\N,True,9.4,16.0,movie,On Thin Ice,On Thin Ice,False,2019,0,75,"Documentary,Drama,Sport",0,0,0,60-90
19152450,3,US,\N,\N,literal English title,False,6.1,216.0,movie,Lovefucked,Lovefucked,False,2019,0,106,"Drama,Romance",0,0,0,90-120
18873466,5,US,\N,imdbDisplay,\N,False,6.2,1057.0,movie,15 Minutes of War,L'intervention,False,2019,0,98,"Action,Drama,History",0,0,0,90-120
18860300,2,US,\N,\N,\N,False,6.9,11.0,movie,Zona,Zona,False,2019,0,63,Documentary,0,0,0,60-90
18840996,2,US,\N,imdbDisplay,\N,False,NaN,NaN,movie,Homemade,Homemade,False,2019,0,90,"Documentary,War",0,0,0,60-90
19126547,1,US,\N,\N,\N,True,NaN,NaN,movie,The League of Explordinaires,The League of Explordinaires,False,2019,0,60,Documentary,0,0,0,30-60
19275197,2,US,\N,\N,\N,True,NaN,NaN,movie,Roadie: My Documentary,Roadie: My Documentary,False,2019,0,78,Documentary,0,0,0,60-90
19122884,25,US,\N,imdbDisplay,\N,True,6.0,10920.0,movie,The Kid Who Would Be King,The Kid Who Would Be King,False,2019,0,120,"Action,Adventure,Family",0,0,0,90-120
19199140,3,US,\N,imdbDisplay,\N,True,7.1,92.0,movie,Blood Machines,Blood Machines,False,2019,0,50,"Adventure,Music,Sci-Fi",0,0,0,30-60
19312164,1,US,\N,\N,\N,True,NaN,NaN,movie,To a Dead Friend,To a Dead Friend,False,2020,0,77,Drama,0,0,0,60-90
19012107,3,US,\N,imdbDisplay,\N,False,6.9,464.0,movie,Kingdom,Kingudamu,False,2019,0,134,"Action,History,War",2019,0,0,120-180
19304556,3,US,\N,imdbDisplay,\N,True,NaN,NaN,movie,The Last Full Measure,The Last Full Measure,False,2020,0,110,"Drama,War",0,0,0,90-120
18815086,1,US,\N,\N,\N,True,NaN,NaN,movie,James Hubbell - Between Heaven and Earth,James Hubbell - Between Heaven and Earth,False,2019,0,68,Documentary,0,0,0,60-90
19324547,1,US,\N,\N,\N,False,NaN,NaN,movie,Walking In Darkness II,Walking In Darkness II,False,2021,0,96,Documentary,0,0,0,90-120
19204805,5,US,\N,alternative,\N,False,2.4,146.0,movie,Girl/Girl Scene,Girl/Girl Scene,False,2019,0,122,"Comedy,Drama,Romance",0,0,0,120-180
19198762,3,US,\N,\N,new title,True,6.0,425.0,movie,Blood Will Tell,La Misma Sangre,False,2019,0,113,"Drama,Mystery,Thriller",2019,0,0,90-120
19294066,5,US,\N,imdbDisplay,\N,False,7.3,5743.0,movie,Batla House,Batla House,False,2019,0,146,"Action,Drama,Thriller",0,0,0,120-180
19139288,3,US,\N,working,\N,True,NaN,NaN,movie,A Certain Magical Pimpdex: Extended Edition,A Certain Magical Pimpdex: Extended Edition,False,2019,0,263,Animation,0,0,0,Long
19086059,37,US,\N,\N,\N,False,5.9,39861.0,movie,Annabelle Comes Home,Annabelle Comes Home,False,2019,0,106,"Horror,Mystery,Thriller",0,0,0,90-120
19321509,1,US,\N,\N,\N,False,NaN,NaN,movie,Pink Hill,Pink Hill,False,2020,0,75,Drama,0,0,0,60-90
18991358,2,US,\N,\N,\N,True,8.5,954.0,movie,What's My Name: Muhammad Ali,What's My Name: Muhammad Ali,False,2019,0,165,"Biography,Documentary,Sport",0,0,0,120-180
19113168,2,US,\N,\N,new title,False,7.0,70.0,movie,The Devil's Machine,Automata,False,2019,0,95,Horror,0,0,0,90-120
18949027,5,US,\N,\N,\N,False,6.8,179.0,movie,"Family Romance, LLC.","Family Romance, LLC.",False,2019,0,89,Drama,0,0,0,60-90
19101479,6,US,\N,imdbDisplay,\N,False,7.9,12240.0,movie,The Farewell,The Farewell,False,2019,0,100,"Comedy,Drama",0,0,0,90-120
19229680,4,US,en,alternative,\N,True,6.7,103637.0,movie,Pokémon Detective Pikachu,Pokémon Detective Pikachu,False,2019,0,104,"Action,Adventure,Comedy",0,0,0,90-120
18817421,2,US,\N,\N,YIVO translation,False,6.1,27.0,movie,A Mero Hajur 3,A Mero Hajur 3,False,2019,0,125,"Drama,Romance",0,0,0,120-180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19284867,1,US,\N,\N,\N,False,NaN,NaN,movie,Revenge,Revenge,False,2019,0,73,Horror,2019,0,0,60-90
19198297,1,US,\N,\N,\N,True,NaN,NaN,movie,Quail Lake,Quail Lake,False,2019,0,89,Drama,0,0,0,60-90
18915601,1,US,\N,alternative,\N,False,NaN,NaN,movie,Councilwoman,Councilwoman,False,2019,0,71,Documentary,0,0,0,60-90
19111115,20,US,\N,imdbDisplay,\N,True,5.4,26202.0,movie,The Curse of La Llorona,The Curse of La Llorona,False,2019,0,93,"Horror,Mystery,Thriller",0,0,0,90-120
19088398,35,US,\N,imdbDisplay,\N,True,7.6,232495.0,movie,Spider-Man: Far from Home,Spider-Man: Far from Home,False,2019,0,129,"Action,Adventure,Sci-Fi",0,0,0,120-180
19169113,2,US,\N,\N,\N,True,7.4,8.0,movie,Act of Contrition,Act of Contrition,False,2019,0,100,"Crime,Drama",0,0,0,90-120
18903025,6,US,\N,imdbDisplay,\N,True,6.2,2549.0,movie,Finding Steve McQueen,Finding Steve McQueen,False,2019,0,91,"Crime,Romance",0,0,0,90-120
18759392,2,US,\N,imdbDisplay,\N,False,NaN,NaN,movie,Dear Frank,Dear Frank,False,2019,0,93,"Comedy,Drama,Thriller",0,0,0,90-120
18986415,18,US,\N,\N,\N,False,6.0,9471.0,movie,Dora and the Lost City of Gold,Dora and the Lost City of Gold,False,2019,0,102,"Adventure,Family",0,0,0,90-120
19239530,5,US,\N,\N,\N,False,5.6,1476.0,movie,Burn,Burn,False,2019,0,88,Thriller,0,0,0,60-90
18837171,1,US,\N,\N,\N,False,7.3,19.0,movie,Hurley,Hurley,False,2019,0,83,Documentary,0,0,0,60-90
18996128,4,US,\N,\N,\N,False,4.8,1374.0,movie,Tone-Deaf,Tone-Deaf,False,2019,0,87,"Comedy,Horror,Thriller",0,0,0,60-90
19048766,2,US,\N,imdbDisplay,\N,True,NaN,NaN,movie,Alice Cooper: Live from the Astroturf,"Live from the Astroturf, Alice Cooper",False,2019,0,70,"Documentary,Music",0,0,0,60-90
19011757,1,US,\N,\N,\N,True,7.1,136.0,movie,To the Stars,To the Stars,False,2019,0,109,Drama,0,0,0,90-120
18951560,1,US,\N,\N,\N,True,NaN,NaN,movie,Love or Laughs,Love or Laughs,False,2019,0,81,"Action,Comedy,Romance",0,0,0,60-90
19304659,1,US,\N,\N,\N,True,NaN,NaN,movie,Moose on the Loose II,Moose on the Loose II,False,2020,0,99,Comedy,0,0,0,90-120
19011869,2,US,\N,imdbDisplay,\N,True,8.1,84.0,movie,Kinky Boots: The Musical,Kinky Boots: The Musical,False,2019,0,135,Musical,0,0,0,120-180
19279682,17,US,\N,imdbDisplay,\N,True,7.4,78744.0,movie,Rocketman,Rocketman,False,2019,0,121,"Biography,Drama,Music",0,0,0,120-180
19176456,1,US,\N,\N,\N,False,NaN,NaN,movie,Punch Shot,Punch Shot,False,2019,0,64,Documentary,0,0,0,60-90
19316075,1,US,\N,\N,\N,False,NaN,NaN,movie,East Nashville: Somewhere Over the River,East Nashville: Somewhere Over the River,False,2020,0,67,Music,0,0,0,60-90
18886338,1,US,\N,\N,\N,True,NaN,NaN,movie,The Tricky Part,The Tricky Part,False,2019,0,90,Biography,0,0,0,60-90
19196144,1,US,\N,\N,\N,False,5.5,279.0,movie,Rattlesnakes,Rattlesnakes,False,2019,0,85,Thriller,0,0,0,60-90
19196709,5,US,\N,imdbDisplay,\N,False,6.9,8909.0,movie,Blinded by the Light,Blinded by the Light,False,2019,0,118,"Comedy,Drama,Music",0,0,0,90-120
18946064,1,US,\N,\N,\N,True,NaN,NaN,movie,Trojan Base Alpha,Trojan Base Alpha,False,2019,0,145,Sci-Fi,0,0,0,120-180
19121606,3,US,\N,working,\N,True,NaN,NaN,movie,Dropa,Dropa,False,2019,0,101,"Drama,Sci-Fi,Thriller",0,0,0,90-120
18998092,2,US,\N,alternative,\N,False,5.1,124.0,movie,The Husband,The Husband,False,2019,0,87,Thriller,0,0,0,60-90
18842318,1,US,\N,\N,\N,True,NaN,NaN,movie,Homecoming - Special Edition Director's Cut,Homecoming - Special Edition Director's Cut,False,2019,0,125,Horror,0,0,0,120-180
19023381,4,US,en,\N,\N,False,5.7,2144.0,movie,Nancy Drew and the Hidden Staircase,Nancy Drew and the Hidden Staircase,False,2019,0,89,"Comedy,Crime,Drama",0,0,0,60-90
19035164,3,US,\N,\N,\N,False,5.7,24.0,movie,Super Bear,Super Bear,False,2019,0,85,Animation,0,0,0,60-90
19076451,10,US,\N,\N,\N,True,7.1,191178.0,movie,Shazam!,Shazam!,False,2019,0,132,"Action,Adventure,Comedy",0,0,0,120-180

In [586]:
data_new_prepped = full_pipeline.transform(some_new)

In [587]:
lin_reg.predict(data_new_prepped)

array([-0.81673106, -0.76313335, -0.89205083, -0.7737599 , -0.91237649,
       -0.84582326, -0.84963947, -0.86650393, -0.81090957, -0.81127765,
       -0.81479056, -0.82961378, -0.86528124, -1.81603927, -0.82446246,
       -1.81470095, -0.81802472, -2.82015405, -0.73906684, -0.8413798 ,
       -0.82376319, -0.77362745, -0.80594827, -1.8166861 , -0.8458381 ,
       -0.86742593, -0.85595269, -0.87270311, -0.73587691, -0.81184628,
       -0.8134969 , -0.86896081, -0.88225349, -0.85521865, -0.83203248,
       -0.83508457, -0.84595211, -0.81414373, -0.81862689, -0.83944209,
       -0.81862689, -1.82024367, -1.81664144, -0.85796436, -0.81382031,
       -0.85956846, -0.81090957, -0.81072013, -0.81252665, -0.82171592,
       -0.88003918, -0.81895031, -0.80398862, -0.81386497, -0.89359234,
       -0.81867155, -0.81765665, -0.88714731, -0.78224154, -0.8115564 ,
       -0.87027804, -0.81959714, -0.86350142, -0.84744775, -0.8166864 ,
       -0.8134969 , -0.88286019, -0.86349288, -0.80370862, -0.83341428,
       -0.83153374, -0.80884867, -0.77037119, -0.86946539, -0.8115564 ,
       -0.85983875, -0.88489336, -1.81183486, -0.81252665, -0.6887148 ,
       -0.81862689, -0.81039523, -0.81899497, -0.81608422, -0.81446715,
       -0.85492721, -0.8115918 , -0.81127765, -1.82052243, -0.81127765,
       -0.84259198, -0.8341877 , -0.81834814, -0.83272455, -0.87300143,
       -0.82990141, -0.84730653, -0.87545736, -0.86770793, -0.81640764,
       -0.86013048, -0.89515326, -0.84372261, -0.82408326, -0.77768706,
       -0.85587314, -0.87959098, -0.78825364, -0.83357143, -0.86981575,
       -0.81504829, -0.85668728, -0.87465367, -0.70031828, -0.8804305 ,
       -0.81386497, -0.82937339, -0.86651453, -0.81862689, -0.912526  ,
       -0.84746594, -1.81830318, -0.81543739, -0.86885546, -2.76498393,
       -0.81386497, -0.81511398, -0.88974436, -0.81608422, -0.83347661,
       -0.82969723, -0.81992056, -0.81187521, -0.81127765, -0.84029978,
       -0.80678827, -0.81971522, -0.79149834, -0.87169763, -0.81414373,
       -0.86595679, -0.8061862 , -0.81252665, -0.78366947, -0.84019866,
       -0.77606998, -0.83118108, -0.77136354, -0.86820242, -0.81090957,
       -0.85353858, -0.80648112, -1.81955218, -0.81414373, -0.90147894,
       -0.8134969 , -0.81860586, -0.83182507, -0.85729427, -0.66517804,
       -1.81927342, -0.86547986, -0.87827646, -0.82274814, -0.81746894,
       -0.85920007, -0.81354156, -0.90539061, -0.81867155, -0.83577737,
       -0.80573736, -0.8164523 , -0.81280541, -0.76726382, -0.80981141,
       -0.86364417, -0.88339559, -0.78092122, -0.83250989, -1.81183486,
       -0.81332374, -0.73906684, -0.88692264, -0.86723217, -0.81188472,
       -0.8166864 , -0.85676461, -0.79912409, -1.81955218, -0.86892612,
       -0.83004698, -0.88328054, -0.81377566, -0.81414373, -0.86772694,
       -0.81442249, -0.87959098, -0.79678917, -0.83426929, -0.77833543,
       -0.812482  , -1.81664144, -0.78951558, -0.86240982, -0.78427293,
       -0.83457336, -0.91163634, -0.79574262, -1.81797976, -0.80295318,
       -1.8032366 , -2.81276015, -0.77089533, -1.81146679, -0.85937611,
       -0.81414373, -0.83157306, -0.8166864 , -0.8840388 , -0.864247  ,
       -0.8171934 , -2.81886039, -0.82077604, -0.81862689, -0.81479056,
       -0.81402964, -0.80203742, -0.80100304, -0.81612888, -0.90640914,
       -0.81774596, -0.77768706, -1.81183486, -0.81309234, -0.80318112,
       -0.81700982, -0.78310317, -0.81802472, -0.81959714, -1.80550051,
       -0.82966082, -0.87852806, -0.81867155, -0.82508119, -0.81090957,
       -0.81285007, -0.90412514, -0.84341737, -0.86406485, -0.78291858,
       -0.81414373, -0.83237849, -0.81765665, -0.88701502, -0.81511398,
       -0.82401841, -0.8640072 , -0.82686095, -1.8032366 , -0.81479056,
       -0.837264  , -0.87536055, -0.81409907, -0.83315123, -0.87702104,
       -0.84096411, -0.8744206 , -0.79841417, -0.83663215, -1.82084585,
       -0.81737789, -0.85259934, -1.81183486, -1.82084585, -0.85630688,
       -0.81090957, -0.84197366, -0.81737789, -0.88889124, -0.81576081,
       -0.82606755, -0.90266376, -0.75353114, -0.81636298, -0.81640764,
       -0.82780278, -0.7970454 , -1.81183486, -0.81893821, -0.79851094,
       -0.79616294, -0.8186554 , -0.88498875, -0.87069003, -0.83154219,
       -0.81511398, -0.83901876, -0.81992056, -0.76902539, -0.81608422,
       -0.8379958 , -0.81127765, -0.85073445, -1.81506902, -0.83876357,
       -0.78062108, -0.86851695, -0.79604068, -0.85370475, -0.80982578,
       -0.81123299, -0.81539274, -0.81621013, -0.81899497, -0.85471509,
       -0.79826951, -0.81090957, -0.81959714, -0.81317348, -0.8697841 ,
       -1.81830318, -0.89038302, -0.81752433, -0.8715711 , -0.82950315,
       -0.85759334, -0.8668416 , -0.81959714, -0.81090957, -0.82524461,
       -0.81576081, -0.83376372, -0.81474591, -0.81470783, -0.81673106,
       -1.81345194, -0.75966129, -0.87450871, -0.81345224, -0.80877963,
       -0.81899497, -4.81461072, -0.77965635, -0.81992056, -0.82952456,
       -1.81183486, -0.85207545, -1.82052243, -0.81640764, -0.81603957,
       -0.79042685, -0.85665533, -0.83091066, -0.85997375, -0.81345224,
       -0.87753815, -0.81543739, -0.81673106, -0.81576081, -0.81996521,
       -0.81090957, -0.77968532, -0.72899953, -0.8236687 , -0.87252628,
       -0.81867155, -0.81920354, -0.81252665, -0.79054698, -0.77930414,
       -0.8481129 , -0.81366625, -0.81215858, -0.79391746, -0.82856969,
       -0.85426376, -0.81479056, -0.81158594, -0.83409784, -0.82384373,
       -0.81127765, -0.85475406, -1.82121392, -0.81474591, -0.81959714,
       -0.86478422, -0.87830003, -0.81289472, -0.84352485, -0.77766165,
       -0.82566216, -0.8757206 , -0.88803122, -0.87592741, -0.86128766,
       -0.82381869, -0.85902006, -0.84259198, -0.6409866 , -0.77922063,
       -0.79820661, -0.8105415 , -0.82150326, -0.84971864, -0.858681  ,
       -0.74528402, -0.81187982, -0.82824963, -0.81072013, -0.77669316,
       -0.812962  , -0.81220324, -0.81090957, -0.7682782 , -0.86258919,
       -0.85214433, -0.81317348, -1.81183486, -0.7763934 , -0.78156805,
       -0.83316297, -0.73789817, -0.81576901, -0.88031661, -0.8143225 ,
       -0.77801048, -0.82186259, -0.81521673, -2.76983517, -0.86003626,
       -0.80231132, -0.81382031, -0.65641863, -0.81700982, -0.8902843 ,
       -0.83493268, -1.81183486, -0.77833389, -0.81414373, -0.81576081,
       -0.91148869, -1.81183486, -0.78301823, -0.71924499, -0.80480495,
       -0.88086818, -1.81955218, -0.87464167, -0.77968532, -0.81090957,
       -0.86955519, -0.8405002 , -0.89767575, -0.81798006, -0.84503888,
       -0.88127962, -0.8115564 , -0.83030642, -0.85700694, -0.81802472,
       -0.83885385, -0.81543739, -0.8118485 , -0.84230479, -0.81927373,
       -0.81700982, -0.81931838, -0.8556199 , -0.81573596, -1.81567119,
       -0.88915017, -0.79240014, -0.85288758, -0.81202302, -0.81414373,
       -0.7682782 , -0.82209874, -0.87618079, -0.81382031, -0.81737789,
       -0.81506932, -0.9033526 , -0.89679064, -0.81090957, -0.81414373,
       -0.80468505, -0.85976112, -0.81673106, -1.81922877, -0.82140958,
       -0.81899497, -0.87233427, -0.8177013 , -0.85503489, -0.81446715,
       -1.81442219, -0.82232534, -0.8134969 , -0.88688549, -0.81414373,
       -0.83889293, -0.85189767, -0.8547327 , -0.86536428, -0.79841417,
       -0.82661087, -1.81603927, -0.86969682, -1.8179351 , -0.81149677,
       -0.85642814, -0.83057944, -0.87549318, -0.91505079, -0.85930563,
       -0.8193768 , -2.81627306, -1.81506902, -0.86022351, -0.83286687,
       -0.81765665, -0.81479698, -0.81280541, -0.85274123, -0.81117881,
       -0.86279661, -0.82940265, -0.87073889, -0.81742254, -0.81461943,
       -0.81673106, -0.83812214, -0.88248698, -0.85029567, -0.81302942,
       -0.81608422, -0.81321814, -0.86045299, -1.81631802, -0.82619925,
       -0.85605483, -0.77954464, -0.80651572, -0.81220324, -0.81608422,
       -0.81446715, -0.86611594, -0.81257131, -0.8115564 , -0.81673106,
       -0.84034699, -0.82824963, -0.84012849, -0.85544868, -0.82416278,
       -0.82358734, -0.78597627, -0.78502456, -0.80979439, -0.78991615,
       -0.84745137, -0.85855466, -0.87767765, -0.81215858, -0.80328156,
       -0.30424926, -0.77681077, -0.77773374, -0.82778891, -0.81580547,
       -0.83577737, -1.81506902, -0.81414373, -0.84201584, -0.86664345,
       -0.86989669, -0.81576081, -0.89542839, -0.85776265, -0.81252665,
       -0.81280541, -0.81830348, -0.84033622, -0.78670893, -0.87536076,
       -0.81127765, -0.81543739, -0.88054637, -0.84941853, -0.80586889,
       -0.85672718, -0.81409907, -0.80204128, -0.80619231, -0.81777149,
       -0.81799127, -0.82971998, -0.81184628, -0.81612888, -0.82587473,
       -0.8125958 , -0.82724626, -0.77738953, -0.81290816, -0.81090957,
       -0.81640764, -0.80492443, -0.8193768 , -0.80263538, -0.83246288,
       -0.81127765, -0.83598207, -0.90020264, -0.82324304, -0.81576081,
       -0.81127765, -0.76680657, -0.81127765, -0.81673106, -1.81922877,
       -0.81414373, -0.88603909, -0.85435339, -0.77179681, -0.85932925,
       -0.87505308, -0.81927373, -0.81830348, -0.81996521, -0.87133072,
       -0.87762601, -0.80554547, -0.82602884, -0.87295232, -0.868593  ,
       -0.81123299, -0.91201475, -0.89321703, -0.81127765, -1.81470095,
       -0.87113503, -0.77865731, -0.85968235, -0.79030941, -0.7729105 ,
       -0.81895031, -0.86316988, -0.84235073, -0.85834646, -0.81090957,
       -0.87614729, -0.81123299, -0.87131992, -0.82246763, -0.83487003,
       -1.81215828, -0.81414373, -0.83458653, -0.86257388, -0.79881128,
       -0.83388511, -0.81862689, -1.78903673, -0.90355366, -0.77604442,
       -1.81345194, -0.89275926, -0.81382031, -0.8616265 , -0.82409371,
       -0.81971522, -0.85906633, -0.83539982, -0.84878128, -0.79733476,
       -0.83458785, -0.8437857 , -0.78065445, -0.78989481, -0.83371848,
       -0.81862689, -0.82552612, -0.81382031, -1.81765634, -0.81332374,
       -0.76559953, -0.87516595, -0.85039021, -1.81312852, -0.8722168 ,
       -1.81442219, -0.81414373, -0.81382031, -0.82750739, -0.8941744 ,
       -0.81386497, -0.84819744, -0.87821849, -1.81830318, -0.82982407,
       -0.81890526, -1.81442219, -0.85176858, -0.8105415 , -0.81705447,
       -0.77801048, -0.81192448, -0.82757577, -0.85777532, -1.77537819,
       -0.81576081, -2.81276015, -0.8714111 , -0.81182612, -0.81382031,
       -0.82567064, -0.8115564 , -0.83756303, -0.81090957, -0.81220324,
       -0.92344519, -0.81391485, -0.81895031, -0.81090957, -0.81543739,
       -0.81608422, -0.81798006, -0.83701301, -0.86693062, -0.78573053,
       -0.83423824, -0.84730392, -0.75353114, -0.88038882, -0.81834814,
       -0.81354156, -0.81123299, -2.81276015, -0.83116627, -0.79171948,
       -0.81765665, -0.83334733, -0.85668728, -0.790908  , -0.888277  ,
       -1.81890535, -0.89445181, -0.80450122, -0.81737789, -1.81183486,
       -0.81090957, -0.86970459, -0.85970133, -0.81090957, -0.84479135,
       -0.8115564 , -0.82393609, -0.87966344, -0.8115564 , -1.81830318,
       -0.88813178, -0.81145169, -0.81705447, -0.89947154, -0.8348807 ,
       -0.88036259, -0.86869424, -0.82038581, -0.82141233, -0.8145118 ,
       -0.83078398, -1.82084585, -0.83981986, -0.88396547, -0.86723217,
       -0.85814543, -2.76983517, -0.82619925, -0.81576081, -1.81539243,
       -0.80586889, -0.81895031, -0.86058862, -0.81784828, -0.86522206,
       -0.85307224, -0.8099837 , -0.79846488, -0.75764908, -0.82028863,
       -0.87194392, -0.81479056, -0.84616573, -0.77477632, -0.80679181,
       -0.77951601, -0.8358937 , -0.82685478, -0.86050522, -0.87700536,
       -0.85238921, -0.80716255, -1.81955218, -1.78022943, -0.81899497,
       -0.81576081, -0.83522223, -0.86474079, -0.76477172, -0.80536245,
       -0.81090957, -0.84674087, -0.81344448, -0.86058862, -0.84350674,
       -0.8256998 , -0.82041836, -0.86853932, -0.81257131, -0.80650979,
       -0.87692056, -0.81640764, -0.81414373, -0.81187982, -0.87168767,
       -0.86273077, -0.89417732, -0.81474591, -0.82246763, -0.88921737,
       -0.81285007, -0.90862865, -0.90061727, -0.84328007, -0.81479056,
       -0.8392936 , -1.8166861 , -1.81899466, -0.77304809, -0.81192448,
       -0.81830348, -1.8179351 , -0.87959169, -0.81737789, -0.85130406,
       -0.87044173, -0.83470284, -0.83522223, -0.84427483, -0.80843992,
       -0.84416829, -0.77865731, -0.81316564, -0.91895778, -0.8134969 ,
       -0.87463358, -0.88215564, -0.80353929, -0.82274814, -0.8214615 ,
       -0.85133157, -0.83779491, -0.78654745, -0.81090957, -0.88351539,
       -0.80951944, -0.85902097, -0.77509974, -0.89696886, -0.81774596,
       -0.84656151, -0.87135428, -1.81797976, -0.87921153, -0.79381006,
       -0.78158782, -0.82950315, -0.81252665, -0.76477528, -0.83477749,
       -0.83233201, -0.81867155, -0.84999729, -0.81959714, -0.79478652,
       -0.85891591, -0.81640764, -0.81830348, -1.81317318, -0.85434466,
       -0.8115564 , -0.81215858, -0.81090957, -0.80629525, -0.81090957,
       -0.9123792 , -0.81252665, -0.85858817, -0.81543739, -0.86954177,
       -0.77768706, -0.81862689, -0.74744609, -0.89342604, -0.89294159,
       -0.76720268, -0.78306531, -0.78442537, -0.819079  , -0.81377566,
       -0.8514478 , -0.78189147, -0.81543739, -0.90669242, -0.81127765,
       -0.79991456, -0.85283446, -0.79453406, -1.81858193, -0.81039671,
       -0.85755975, -0.86461236, -0.83947921, -0.81187982, -0.8105415 ,
       -0.78397221, -0.85192687, -0.80319006, -0.85082168, -0.86618432,
       -0.83616173, -0.78124464, -0.81571615, -0.86724742, -0.85854083,
       -0.81123299, -0.78189147, -0.78592436, -0.81737789, -0.80144631,
       -1.81825852, -0.84702904, -0.81992056, -0.89830444, -0.81442249,
       -0.87683668, -0.86304873, -0.8003311 , -2.81276015, -0.76265758,
       -0.81465112, -0.80247595, -0.82901004, -0.78688257, -0.81543739,
       -0.84178936, -0.82045291, -0.80910305, -0.86772332, -1.81280511,
       -0.77324514, -1.81183486, -0.79153381, -0.84234808, -0.80080671,
       -0.88278776, -0.86099483, -0.81576081, -0.72191528, -1.81409877,
       -0.81640764, -0.81123299, -0.81705447, -0.81256784, -0.62993233,
       -0.87382628, -0.85055254, -0.81927373, -0.83674718, -0.83121793,
       -0.86798966, -0.81571112, -0.81737789, -0.86482868, -0.81382031,
       -1.81825852, -0.84836697, -0.76774424, -0.81931838, -1.81927342,
       -0.81090957, -0.83128161, -0.84999427, -0.77445291, -0.8166864 ,
       -0.82281383, -0.78092122, -0.80338167, -0.83549314, -0.65641863])

In [1485]:
#SVR.predict(data_new_prepped)

array([20.92380849, 20.92380849, 20.92380849,  0.08065061, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849,  1.14653466, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849,  1.04094734, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849, 20.92380849,
       20.92380849, 20.92380849, 20.92380849, 20.92380849,  0.09042451])

In [588]:
tree_reg.predict(data_new_prepped)

array([ 1.        , -3.        , -1.        , -2.        , -2.        ,
        1.        , -2.        , -1.        , -1.        , -1.        ,
       -2.        , -2.        ,  1.        ,  1.        , -2.        ,
       -2.        , -3.        , -2.        , -1.5       , -2.        ,
       -2.        , -3.        , -2.        ,  1.        , -1.        ,
       -2.        , -1.        ,  1.        , -3.        , -1.        ,
       -2.        , -1.        , -3.        , -3.        , -1.        ,
       -1.        , -2.        , -2.        , -4.        , -1.        ,
       -4.        , -1.        , -2.        , -1.        , -2.        ,
       -2.        , -1.        , -2.        , -2.        ,  1.        ,
       -1.        , -4.        , -2.        , -1.        , -3.        ,
       -1.        , -4.        , -1.        , -2.        , -2.        ,
        1.        , -1.        , -4.        , -1.        , -4.        ,
       -2.        , -3.        , -3.        , -2.        , -2.        ,
       -2.        , -1.        , -2.        ,  1.        , -2.        ,
       -2.        , -3.        , -2.        , -2.        , -2.        ,
       -4.        , -2.        , -1.        ,  1.        , -2.        ,
       -2.        , -1.        , -1.        , -2.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        ,  1.        ,
       -1.        , -2.        , -1.        , -1.        ,  1.        ,
       -1.        ,  1.        , -1.        , -1.        , -3.        ,
        1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        ,  1.        , -1.        ,  1.        , -1.        ,
       -1.        , -2.        , -3.        , -4.        , -1.        ,
       -2.        , -3.        ,  1.        , -1.        , -2.        ,
       -1.        ,  1.        , -1.        ,  1.        , -2.        ,
       -1.        , -1.        , -1.        , -1.        , -2.        ,
       -2.        , -1.        , -1.        , -1.        , -2.        ,
       -1.        , -1.        , -2.        , -1.        , -2.        ,
       -3.        , -1.        , -3.        , -1.        , -1.        ,
       -1.        , -1.        , -2.        , -2.        , -1.        ,
       -2.        , -1.        , -1.        ,  1.        , -1.        ,
       -1.        , -2.        , -3.        , -3.        , -2.        ,
       -2.        , -1.        , -2.        , -1.        , -1.        ,
       -2.        ,  1.        , -3.        , -2.        , -1.        ,
       -2.        , -1.        , -3.        , -1.        , -2.        ,
       -2.        , -1.5       , -1.        , -1.        , -1.        ,
       -4.        , -2.        , -2.        , -2.        , -3.        ,
       -1.        , -3.        , -3.        , -2.        , -3.        ,
       -3.        , -1.        , -2.        , -1.        , -2.        ,
       -3.        , -2.        , -1.        , -1.        , -1.        ,
       -1.        , -3.        , -1.        , -3.        , -2.        ,
        1.        , -2.        , -3.        , -2.        , -3.        ,
       -2.        , -2.        , -4.        , -1.        , -3.        ,
       -1.        , -2.        , -2.        , -4.        , -2.        ,
        1.        , -2.        , -1.        ,  1.        , -3.        ,
        1.        , -3.        , -2.        , -1.        , -1.        ,
       -4.        , -2.        , -3.        , -1.        , -4.        ,
       -1.        , -1.        , -1.        ,  1.        , -1.        ,
       -2.        , -1.        ,  1.        , -2.        , -1.        ,
       -2.        , -2.        , -4.        ,  1.        ,  1.        ,
       -3.        , -1.        , -1.        ,  1.        , -2.        ,
       -1.        , -3.        , -3.        , -2.        ,  1.        ,
        1.        , -1.        , -2.        ,  1.        , -2.        ,
       -3.        , -2.        , -2.        , -2.        , -2.        ,
       -1.        ,  1.        , -3.        , -1.        ,  1.        ,
       -2.        , -3.        , -2.        , -3.        ,  1.        ,
        1.        ,  1.        , -2.        , -1.        , -1.        ,
       -2.        , -2.        , -3.        , -2.        ,  1.        ,
        1.        , -2.        , -1.        , -2.        ,  1.        ,
       -2.        , -1.        , -2.        , -2.        , -1.        ,
       -1.        , -1.        , -1.        , -3.        ,  1.        ,
       -1.        , -3.        , -2.        , -1.        , -2.        ,
        1.        , -1.        , -1.        , -2.        , -1.        ,
       -3.        , -1.        , -1.        , -1.        , -1.        ,
       -3.        , -1.        , -1.        , -1.        , -1.        ,
        1.        , -1.        , -3.        , -2.        ,  1.        ,
       -2.        , -2.        , -1.        , -3.        , -1.66666667,
       -1.        , -2.        , -1.5       , -1.        , -1.        ,
       -2.        , -2.        , -2.        ,  1.        , -3.        ,
        1.        , -3.        , -1.        , -2.        , -3.        ,
       -1.        ,  1.        ,  1.        ,  1.        , -1.        ,
       -1.        , -2.        ,  1.        , -1.        , -2.        ,
       -1.        ,  1.        , -2.        , -2.        , -3.        ,
       -2.        , -1.        , -3.        , -1.        , -1.        ,
       -3.        , -2.        , -1.        ,  1.        , -2.        ,
       -1.        , -2.        , -1.        , -3.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -2.        ,
        1.        , -1.        , -3.        , -1.        , -2.        ,
       -2.        , -2.        , -1.        , -3.        , -1.        ,
       -2.        , -3.        , -1.        , -2.        , -2.        ,
        1.        , -2.        , -1.        , -2.        ,  1.        ,
       -1.        , -2.        , -1.        , -1.        , -2.        ,
       -2.        , -2.        , -2.        , -3.        , -3.        ,
        1.        , -1.        , -1.        , -3.        ,  1.        ,
       -3.        , -1.        , -1.        , -2.        , -2.        ,
        1.        , -2.        , -2.        , -4.        , -1.        ,
        1.        , -2.        , -3.        , -2.        ,  1.        ,
       -1.        , -2.        , -1.        , -2.        , -2.        ,
       -1.        , -2.        , -1.        , -2.        , -1.        ,
        1.        , -1.        , -1.        , -4.        , -1.        ,
       -2.        , -2.        , -1.        , -2.        , -3.        ,
       -1.        ,  1.        ,  1.        , -2.        , -1.        ,
       -4.        , -1.        , -3.        , -1.        , -2.        ,
       -1.        , -1.        , -1.        , -2.        , -2.        ,
       -1.        , -1.        , -1.        , -2.        , -3.        ,
       -3.        , -1.        , -3.        , -1.        , -2.        ,
       -1.        , -3.        ,  1.        , -2.        , -1.        ,
       -1.        , -1.        , -3.        , -2.        , -2.        ,
       -2.        , -1.        , -2.        , -3.        , -2.        ,
       -2.        , -2.        , -3.        , -3.        , -2.        ,
       -2.        ,  1.        , -2.        , -2.        , -1.5       ,
       -3.        , -1.        , -3.        , -1.        , -4.        ,
        1.        , -2.        , -2.        ,  1.        , -2.        ,
       -4.        , -1.        , -3.        ,  1.        , -2.        ,
       -1.        ,  1.        , -1.        ,  1.        , -1.        ,
        1.        , -1.        , -1.        , -1.        , -2.        ,
        1.        , -1.        , -1.        , -2.        , -1.        ,
       -2.        , -1.        , -2.        , -2.        ,  1.        ,
       -2.        , -3.        , -1.        , -2.        ,  1.        ,
        1.        , -1.        , -2.        , -2.        , -1.        ,
       -2.        , -1.        , -2.        , -1.        , -2.        ,
       -1.        ,  1.        , -3.        , -3.        ,  1.        ,
        1.        , -2.        , -1.        ,  1.        ,  1.        ,
       -1.        , -2.        , -2.        , -1.        , -1.        ,
        1.        ,  1.        , -1.        , -3.        , -2.        ,
       -3.        , -4.        , -1.        , -2.        ,  1.        ,
       -1.        ,  1.        ,  1.        , -1.        , -1.        ,
       -2.        , -3.        , -2.        , -2.        ,  1.        ,
       -1.        , -1.        , -1.        ,  1.        ,  1.        ,
       -1.        ,  1.        , -2.        , -1.        , -1.        ,
        1.        , -2.        ,  1.        , -2.        , -1.        ,
       -1.        , -1.        , -1.        ,  1.        ,  1.        ,
       -1.        ,  1.        , -1.        ,  1.        , -2.        ,
       -2.        , -3.        , -3.        , -1.        ,  1.        ,
        1.        , -1.        , -4.        , -1.        , -3.        ,
       -3.        , -1.        , -2.        , -3.        , -3.        ,
       -1.        , -3.        , -1.        , -1.        , -2.        ,
       -3.        , -3.        , -2.        ,  1.        , -2.        ,
       -4.        , -2.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        ,  1.        , -3.        , -1.        ,
       -2.        , -2.        , -2.        , -1.        , -1.5       ,
       -1.        , -4.        , -2.        , -3.        , -1.        ,
       -2.        , -3.        , -2.        , -2.        ,  1.        ,
       -1.        , -3.        , -1.        , -2.        , -2.        ,
       -1.        , -1.        , -2.        , -2.        , -2.        ,
       -4.        ,  1.        , -2.        ,  1.        , -2.        ,
        1.        , -1.        , -2.        , -2.        , -2.        ,
       -2.        , -2.        , -2.        , -2.        , -2.        ,
       -1.        , -2.        , -2.        , -3.        , -1.        ,
       -2.        , -2.        , -2.        , -3.        , -3.        ,
       -3.        , -1.        , -1.        , -3.        , -2.        ,
        1.        , -2.        , -1.        , -2.        , -2.        ,
       -1.        , -2.        , -2.        , -1.        , -2.        ,
        1.        , -1.        , -4.        , -1.        ,  1.        ,
        1.        , -4.        , -1.        , -3.        , -2.        ,
        1.        ,  1.        , -2.        , -2.        , -1.        ,
       -1.        , -1.        , -2.        ,  1.        , -2.        ,
       -4.        , -1.        ,  1.        , -1.        , -3.        ,
       -2.        , -1.        , -2.        , -3.        , -2.        ,
       -1.        , -1.        , -3.        , -1.        , -1.        ,
       -2.        , -2.        , -2.        , -2.        , -3.        ,
       -3.        , -1.        , -3.        , -3.        ,  1.        ,
       -1.        , -2.        , -1.        , -1.        ,  1.        ,
       -2.        , -2.        , -1.        , -1.        , -1.        ,
       -2.        , -2.        , -1.        ,  1.        , -2.        ,
       -1.        , -4.        ,  1.        , -2.        ,  1.        ,
       -2.        , -1.        , -2.        , -1.        , -1.        ,
       -1.        , -2.        , -1.        , -3.        , -2.        ,
       -2.        , -2.        , -2.        , -2.        ,  1.        ,
       -3.        , -1.5       , -2.        , -2.        , -1.        ,
        1.        , -2.        , -2.        , -1.        , -2.        ,
       -1.        , -1.        , -1.        ,  1.        , -1.        ,
       -1.        ,  1.        , -1.        , -1.        , -2.        ,
        1.        ,  1.        , -2.        , -2.        , -1.        ,
       -2.        , -1.        , -3.        , -3.        , -1.        ,
       -2.        , -3.        , -3.        , -2.        , -2.        ,
       -2.        ,  1.        ,  1.        , -1.        , -1.        ,
       -4.        , -2.        , -2.        , -3.        , -2.        ,
       -3.        , -1.        , -2.        , -1.        , -1.        ,
       -1.        , -3.        , -2.        , -3.        , -2.        ,
       -1.        , -3.        , -1.        , -3.        ,  1.        ,
       -3.        ,  1.        , -1.        , -1.        ,  1.        ,
       -1.        , -2.        , -3.        ,  1.        ,  1.        ,
       -1.        ,  1.        , -3.        ,  1.        , -2.        ,
       -1.        , -1.        , -2.        , -3.        , -1.        ,
       -2.        , -1.        ,  1.        , -1.        , -1.        ,
        1.        ,  1.        , -4.        , -1.        , -2.        ,
       -2.        , -3.        , -1.        , -1.        , -1.        ,
       -2.        , -2.        , -2.        ,  1.        , -2.        ,
       -3.        , -4.        , -1.        , -1.        ,  1.        ,
       -2.        , -2.        , -2.        , -3.        , -3.        ,
        1.        , -3.        ,  1.        , -3.        , -1.        ,
        1.        , -2.        , -1.        , -2.        , -1.8       ,
        1.        , -3.        , -1.        , -2.        , -3.        ,
       -1.        , -2.        , -2.        , -2.        ,  1.        ,
       -1.        , -3.        , -3.        ,  1.        , -1.        ,
       -1.        , -3.        , -1.        , -3.        , -1.        ,
       -2.        , -1.        , -1.        , -3.        , -3.        ,
       -3.        , -3.        , -2.        , -2.        , -2.        ,
       -2.        , -2.        , -1.        , -1.        ,  1.        ,
       -1.        , -1.        , -2.5       , -3.        , -2.        ,
       -2.        , -2.        , -2.        , -2.        , -2.        ,
       -1.        , -4.        ,  1.        ,  1.        , -2.        ,
        1.        , -1.        , -3.        , -1.        , -1.        ,
       -3.        , -2.        , -1.        , -2.        , -1.        ,
       -1.        , -1.        , -3.        , -1.        , -2.        ,
       -2.        , -1.        , -2.        , -1.        , -1.        ,
       -1.        ,  1.        , -2.        , -3.        , -4.        ,
        1.        , -3.        , -1.        , -1.        , -2.        ])

In [589]:
forest_reg.predict(data_new_prepped)

array([-0.575     , -2.25      , -1.3       , -1.95      , -1.75      ,
        0.05      , -1.3       , -1.5       , -1.        , -0.5       ,
       -2.        , -1.025     , -0.85      , -0.125     , -1.        ,
       -2.025     , -2.725     , -2.2       , -1.1875    , -0.65      ,
       -1.625     , -0.75      , -1.6       ,  0.2       , -1.1       ,
       -1.95      , -1.65      , -0.85      , -1.55      , -0.375     ,
       -2.        , -1.225     , -2.05      , -1.875     , -1.15      ,
       -1.175     , -1.3       , -2.        , -4.        , -1.025     ,
       -4.        , -1.25      , -2.4       , -1.425     , -2.        ,
       -1.525     , -1.        , -1.775     , -2.05      , -0.1       ,
       -1.175     , -4.        , -2.        , -0.5       , -2.15      ,
       -1.        , -3.425     , -1.375     , -1.75      , -1.875     ,
       -0.4       , -1.075     , -2.5       , -1.35      , -3.425     ,
       -2.        , -1.625     , -1.875     , -1.1       , -0.725     ,
       -1.3       , -1.325     , -1.75      ,  0.225     , -1.875     ,
       -2.175     , -2.05      , -1.6       , -2.05      , -1.025     ,
       -4.        , -1.125     , -1.        ,  0.325     , -2.        ,
       -1.75      , -1.3875    , -0.5       , -1.5       , -0.5       ,
       -0.925     , -1.1125    , -1.625     , -1.1       , -1.25      ,
       -1.025     , -1.45      , -0.75      , -1.225     , -0.575     ,
       -1.9875    , -0.675     , -0.85      , -1.375     , -2.225     ,
        0.025     , -1.05      , -1.0125    , -0.675     , -1.325     ,
       -1.15      ,  0.2       , -1.25      , -0.5       , -1.275     ,
       -0.5       , -1.025     , -1.85      , -4.        , -1.6375    ,
       -1.225     , -3.        ,  0.        , -1.325     , -2.025     ,
       -0.5       ,  0.        , -1.05      ,  0.325     , -1.525     ,
       -0.85      , -1.075     , -1.1       , -0.5       , -1.075     ,
       -1.35      , -1.375     , -1.05      , -1.425     , -2.        ,
       -1.4       , -1.125     , -2.05      , -1.075     , -1.325     ,
       -2.225     , -0.925     , -0.75      , -1.125     , -1.        ,
       -1.7       , -1.2       , -2.        , -2.        , -1.0375    ,
       -2.        , -1.15      , -0.425     , -0.55      , -0.725     ,
       -1.9       , -1.55      , -1.925     , -1.675     , -1.45      ,
       -2.15      , -0.5       , -1.475     , -1.        , -1.05      ,
       -1.4625    ,  0.275     , -2.45      , -1.9375    , -1.175     ,
       -0.775     , -1.375     , -2.3       , -1.325     , -1.6       ,
       -1.65      , -1.1875    , -1.25      , -1.2       , -1.05      ,
       -3.425     , -1.275     , -1.4625    , -2.        , -1.675     ,
       -1.175     , -1.65      , -2.45      , -2.        , -2.25      ,
       -3.        , -1.05      , -0.775     , -1.2       , -1.975     ,
       -2.45      , -2.4       , -1.05      , -2.1       , -1.        ,
       -1.2375    , -2.25      , -0.15      , -3.        , -1.65      ,
       -0.05      , -1.625     , -2.25      , -2.        , -2.8       ,
       -2.        , -1.275     , -3.425     , -1.25      , -1.85      ,
       -1.6       , -2.6       , -2.        , -4.        , -2.        ,
        0.825     , -1.45      , -1.025     ,  0.375     , -2.        ,
        0.475     , -2.225     , -1.6       , -1.075     , -0.125     ,
       -3.425     , -1.5       , -2.725     , -1.075     , -3.175     ,
       -0.7625    , -1.        , -1.        ,  0.45      , -1.        ,
       -2.05      , -1.0375    , -0.875     , -1.45      , -1.        ,
       -2.        , -0.625     , -3.425     , -0.0625    ,  0.        ,
       -1.8       , -1.425     , -0.8       , -0.05      , -2.        ,
       -0.625     , -2.075     , -3.        , -1.175     , -0.8       ,
        0.1375    , -1.2       , -2.        , -0.05      , -1.5       ,
       -2.725     , -2.125     , -1.6       , -1.5       , -1.75      ,
       -1.        ,  0.15      , -2.725     , -1.05      ,  0.325     ,
       -1.475     , -2.175     , -1.7       , -2.925     , -0.575     ,
        0.1125    ,  0.6       , -1.6       , -1.7125    , -1.        ,
       -1.725     , -1.125     , -2.175     , -1.925     , -0.4375    ,
        0.        , -1.6       , -1.075     , -1.625     ,  0.325     ,
       -1.2       , -0.5       , -2.325     , -2.125     , -0.5875    ,
       -0.85      , -1.45      , -1.1625    , -2.05      ,  0.475     ,
       -1.        , -2.95      , -2.075     , -1.        , -1.825     ,
        0.4375    , -1.        , -1.075     , -2.        , -1.05      ,
       -3.        , -1.3       , -1.025     , -0.75      , -1.275     ,
       -1.525     , -1.35      , -1.075     , -1.        , -1.225     ,
        0.325     , -1.2375    , -2.9       , -1.65      , -0.575     ,
       -2.125     , -1.9       , -1.825     , -2.45      , -1.54166667,
       -1.        , -1.625     , -1.35      , -1.075     , -1.6       ,
       -1.6       , -1.825     , -1.5       , -0.575     , -2.95      ,
        0.8       , -2.125     , -1.05      , -1.4       , -2.45      ,
       -1.475     ,  0.        , -0.575     ,  0.325     , -1.        ,
       -1.        , -0.85      , -0.475     , -1.4625    , -1.625     ,
       -1.        ,  0.55      , -2.05      , -0.95      , -2.225     ,
       -1.35      , -1.2       , -2.4       , -1.1375    , -1.        ,
       -2.05      , -2.        , -0.75      ,  0.1625    , -0.525     ,
       -0.5       , -2.5       , -1.25      , -2.9       , -1.075     ,
       -2.2       , -1.2       , -0.45      , -0.6125    , -1.45      ,
        0.275     , -1.425     , -2.15      , -0.9       , -1.7       ,
       -1.725     , -2.375     , -0.925     , -1.525     , -1.0625    ,
       -1.65      , -2.4       , -1.375     , -1.925     , -1.65      ,
       -0.475     , -1.875     , -1.15      , -1.775     , -0.2       ,
       -0.95      , -1.875     , -1.        , -0.9       , -1.475     ,
       -1.8       , -2.        , -1.6       , -2.225     , -2.25      ,
        0.1       , -0.875     , -1.45      , -2.175     ,  0.95      ,
       -2.225     , -0.8625    , -1.025     , -2.025     , -1.575     ,
        0.15      , -2.        , -1.1       , -3.425     , -1.35      ,
       -0.325     , -1.6       , -2.225     , -2.        ,  0.325     ,
       -1.3625    , -1.6       , -1.0125    , -1.375     , -1.5375    ,
       -1.025     , -2.        , -1.475     , -0.85      , -1.        ,
       -0.625     , -1.4625    , -1.125     , -3.625     , -1.4625    ,
       -1.725     , -1.875     , -1.5625    , -1.525     , -2.725     ,
       -0.975     ,  0.        ,  0.75      , -1.325     , -1.225     ,
       -3.425     , -1.        , -2.05      , -1.2       , -2.425     ,
       -1.225     , -0.825     , -1.25      , -2.        , -2.        ,
       -0.9       , -1.3375    , -1.3       , -2.        , -2.725     ,
       -2.95      , -1.7375    , -1.7       , -1.        , -2.        ,
       -1.075     , -2.35      , -0.575     , -2.        , -1.7875    ,
       -1.        , -1.625     , -2.725     , -2.35      , -2.        ,
       -2.075     , -1.        , -2.        , -2.05      , -2.        ,
       -1.325     , -1.025     , -2.15      , -2.225     , -2.        ,
       -1.05      , -0.125     , -1.25      , -2.4       , -1.45      ,
       -1.675     , -0.925     , -1.8       , -1.1625    , -2.35      ,
        0.025     , -2.6       , -2.125     ,  0.1       , -0.625     ,
       -3.425     , -1.4375    , -2.45      ,  0.        , -1.775     ,
       -2.175     ,  0.0625    , -1.475     ,  0.475     , -1.2125    ,
       -0.575     , -1.1125    , -1.075     , -1.25      , -2.075     ,
        0.325     , -0.5       , -1.9875    , -2.4       , -1.3375    ,
       -1.6       , -0.125     , -1.85      , -1.875     ,  0.325     ,
       -2.        , -2.5625    , -0.5       , -1.875     , -0.575     ,
        0.6       , -1.15      , -1.175     , -2.05      , -1.15      ,
       -1.775     , -0.875     , -1.7       , -0.325     , -1.15      ,
       -1.35      ,  0.225     , -2.175     , -2.4       ,  0.15      ,
       -0.175     , -1.975     , -1.0375    ,  0.2       ,  0.375     ,
       -1.05      , -2.125     , -2.        , -1.2125    , -1.325     ,
       -0.9       ,  0.325     , -1.35      , -2.775     , -2.05      ,
       -2.45      , -3.675     , -1.1625    , -1.875     ,  0.2       ,
       -0.5       ,  0.        ,  0.2       , -0.825     , -1.025     ,
       -2.3625    , -3.        , -1.175     , -1.7125    ,  0.025     ,
       -1.3       , -0.725     , -0.375     ,  0.375     ,  0.275     ,
       -1.5625    , -0.1625    , -1.625     , -1.325     , -1.        ,
       -0.575     , -1.825     ,  0.025     , -1.275     , -1.6       ,
       -0.5       , -1.        , -1.5125    , -0.225     ,  0.325     ,
       -0.5       , -0.2       , -0.5       , -0.575     , -2.        ,
       -2.        , -2.15      , -2.025     , -1.        ,  0.1       ,
       -1.125     , -1.225     , -3.675     , -1.        , -2.2       ,
       -1.975     , -1.05      , -1.775     , -2.15      , -2.05      ,
       -1.        , -1.825     , -1.2625    , -0.5       , -2.025     ,
       -2.3       , -2.225     , -1.85      ,  0.375     , -1.75      ,
       -4.        , -1.5       , -1.05      , -1.075     , -1.        ,
       -1.2       , -1.        , -1.3       , -1.675     , -1.075     ,
       -1.6       , -2.        , -1.025     , -1.45      , -1.2125    ,
       -1.2125    , -4.        , -1.625     , -2.225     , -1.425     ,
       -2.125     , -1.75      , -2.        , -1.975     , -0.175     ,
       -1.375     , -1.8       , -1.3625    , -2.4       , -1.4125    ,
       -1.175     , -1.425     , -1.175     , -1.725     , -0.975     ,
       -4.        ,  0.7375    , -2.        , -0.7       , -1.65      ,
       -0.6125    , -0.525     , -2.225     , -2.05      , -1.575     ,
       -2.075     , -2.        , -2.        , -1.225     , -1.7       ,
       -0.5       , -1.825     , -2.        , -3.        , -1.175     ,
       -2.1       , -2.075     , -1.9       , -2.4       , -2.725     ,
       -2.225     , -0.5       , -1.15      , -2.725     , -1.975     ,
        0.325     , -1.625     , -1.7       , -1.15      , -2.        ,
       -1.025     , -1.875     , -1.225     , -1.        , -1.875     ,
       -0.55      , -1.625     , -4.        , -1.        ,  0.        ,
        0.325     , -3.625     , -1.225     , -2.05      , -1.825     ,
        0.875     ,  0.225     , -1.7       , -1.975     , -1.625     ,
       -0.5       , -1.        , -1.625     ,  0.1       , -1.6       ,
       -3.425     , -1.2       ,  0.2       , -0.925     , -2.15      ,
       -2.        , -1.225     , -1.675     , -2.725     , -1.6       ,
       -1.        , -1.475     , -2.8       , -1.        , -0.475     ,
       -1.875     , -1.8       , -1.875     , -1.875     , -3.        ,
       -1.775     , -1.2       , -2.725     , -2.475     ,  0.925     ,
       -1.175     , -1.875     , -0.7       , -1.675     ,  0.175     ,
       -1.725     , -1.5       , -1.325     , -1.025     , -1.2       ,
       -1.45      , -2.025     , -1.3375    ,  0.325     , -2.125     ,
       -1.025     , -4.        ,  0.25      , -1.6       ,  0.55      ,
       -1.8       , -1.225     , -1.9875    , -0.8875    , -1.        ,
       -0.65      , -2.        , -0.725     , -2.25      , -1.15      ,
       -1.5125    , -0.875     , -1.95      , -1.4       ,  0.525     ,
       -1.75      , -1.3875    , -2.        , -1.95      , -1.        ,
        0.325     , -0.9       , -1.55      , -1.1125    , -0.8       ,
       -1.        , -1.125     , -1.35      ,  0.25      , -0.6125    ,
       -1.3875    , -0.375     , -1.075     , -0.5       , -1.975     ,
       -1.05      , -0.575     , -2.        , -1.875     , -1.2       ,
       -1.5       , -1.0375    , -2.9       , -1.675     , -1.05      ,
       -2.05      , -2.25      , -2.15      , -1.2       , -2.        ,
       -1.175     ,  0.2       ,  0.25      , -0.6875    , -0.5       ,
       -3.675     , -2.4       , -1.5       , -2.725     , -1.825     ,
       -2.3       , -1.5       , -0.9       , -1.6       , -1.2       ,
       -1.4125    , -2.225     , -0.45      , -1.825     , -2.        ,
       -1.        , -2.275     , -1.05      , -1.675     ,  0.65      ,
       -1.7       ,  0.1375    , -1.025     , -1.        ,  0.5       ,
       -0.875     , -2.375     , -2.225     , -0.6875    ,  0.475     ,
       -1.2       , -0.2       , -3.        , -0.825     , -1.85      ,
       -0.975     , -1.275     , -2.05      , -2.125     , -0.4375    ,
       -1.325     , -1.        ,  0.15      , -1.075     , -1.25      ,
       -0.3       , -0.575     , -3.675     , -0.7       , -1.775     ,
       -1.875     , -2.4       , -1.        , -1.15      , -1.        ,
       -1.75      , -2.05      , -1.45      ,  0.        , -1.025     ,
       -2.225     , -4.        , -1.1875    , -0.925     , -0.3625    ,
       -1.4625    , -1.825     , -1.35      , -1.775     , -2.45      ,
       -1.3       , -2.25      ,  0.        , -1.825     , -0.5       ,
        0.85      , -1.825     , -0.15      , -2.4       , -1.605     ,
       -0.5       , -2.05      , -1.2875    , -1.875     , -2.4       ,
       -1.125     , -1.825     , -1.55      , -1.5       ,  0.175     ,
       -1.1625    , -2.3       , -2.95      , -1.1125    , -1.45      ,
       -1.        , -2.25      , -1.3       , -2.725     , -0.1625    ,
       -2.4       , -0.9       , -1.075     , -2.15      , -3.        ,
       -1.8       , -2.25      , -1.725     , -1.625     , -1.075     ,
       -2.        , -1.725     , -1.525     , -1.15      ,  0.        ,
       -1.325     , -1.7625    , -2.2       , -2.25      , -2.05      ,
       -1.6125    , -1.6       , -1.05      , -1.225     , -1.725     ,
       -1.1       , -1.9       ,  0.325     , -0.45      , -2.075     ,
       -0.575     , -1.        , -2.725     , -1.1       , -0.725     ,
       -1.8       , -1.25      , -1.225     , -1.35      , -0.975     ,
       -1.275     , -1.275     , -2.725     , -1.225     , -2.        ,
       -2.4       , -1.425     , -0.625     , -1.        , -1.9       ,
       -1.        ,  0.1       , -1.3       , -2.25      , -3.425     ,
        0.0125    , -2.3       , -0.925     , -1.2625    , -1.1       ])